#!/usr/bin/env python3
r"""analysis: corrected evaluation of E11-core and rep2 saturation candidates.

This script fixes three interpretation hazards from analysis.

1.  The analysis E11-core separator counted only Wang rows generated by spans
    of at most five selected points.  Here we scan the complete core table of
    all 417,199 subspaces of F2^8, derived from the full Wang LUT.

2.  The E11-core construction search in analysis used 19 distinct Boolean
    A-points.  The complete scanner and positive control below are multiset
    aware, because a genuine tensor decomposition may repeat projective
    A-directions unless a separate argument excludes multiplicity.

3.  Saturated contractions force not only term-wise membership in row/column
    spaces, but the existence of independent representatives.  For a saturated
    contraction with participating terms I and rank |I|, the family of B-domain
    subspaces (and separately C-domain subspaces) must admit an independent
    transversal.  By Rado's theorem this is equivalent to

        dim(sum_{s in J} D_s) >= |J| for every J subset I.

The script validates the corrected machinery on the genuine cn122 E11-core
restriction: quotient all 23 A-factors, discard only zero images, and retain the
21 surviving terms with multiplicities and their B/C factors.
"""
from __future__ import annotations

import json
import pickle
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from core_capacity_all_mip import enumerate_subspace_keys  # noqa: E402
from core_capacity_from_wang_lut import CoreQuotient  # noqa: E402
from fixed_A_saturation import (  # noqa: E402
    build_matmul_tensor_f2,
    col_space_basis,
    contraction_matrix,
    gf2_rank_rows,
    in_span,
    intersection_basis,
    linear_membership_test,
    mat_rank_f2,
    read_qmm_terms,
    restrict_terms_f2,
    row_space_basis,
    vec_to_mask,
    verify_terms,
)
from wang_capacity_lazy import subspace_points_from_basis, unpack_basis  # noqa: E402

ROOT = Path("research/research_record")
LUT_PATH = ROOT / "workspace/data/wang_f2_lb20/wang_subspace_lut.pkl"
OUTDIR = ROOT / "workspace/data/core_complete_transversal"


def load_lut(path: Path = LUT_PATH) -> Dict[int, int]:
    with path.open("rb") as f:
        payload = pickle.load(f)
    return {int(k): int(v) for k, v in payload["lut"].items()}


def build_core_constraints(core: CoreQuotient, lut: Dict[int, int]) -> Tuple[List[dict], dict]:
    """Precompute the complete E11-core Wang subspace table.

    Each record stores a bitset of nonzero quotient points in the subspace for
    fast distinct-support occupancy, and enough metadata to reproduce a witness
    row.  Capacities depend on the tested rank s and are computed later as s-L.
    """
    t0 = time.time()
    keys8 = enumerate_subspace_keys(8)
    records = []
    by_dim = Counter()
    by_L = Counter()
    for key8 in keys8:
        key9 = core.key9_from_key8(key8)
        L = lut[key9]
        pts = subspace_points_from_basis(unpack_basis(key8))
        bitset = 0
        for p in pts:
            bitset |= 1 << (p - 1)
        records.append({
            "key8": int(key8),
            "key9": int(key9),
            "dim8": int(key8 & 0xF),
            "dim9": int(key9 & 0xF),
            "L": int(L),
            "point_count": len(pts),
            "point_bitset": bitset,
        })
        by_dim[key8 & 0xF] += 1
        by_L[L] += 1
    meta = {
        "constraint_count": len(records),
        "by_dim8": {str(k): v for k, v in sorted(by_dim.items())},
        "by_full_lut_L": {str(k): v for k, v in sorted(by_L.items())},
        "elapsed_sec": round(time.time() - t0, 3),
    }
    return records, meta


def multiset_counts(A_cols: Sequence[int]) -> Dict[int, int]:
    return {int(k): int(v) for k, v in Counter(int(a) for a in A_cols).items()}


def complete_core_wang_scan(
    label: str,
    A_cols: Sequence[int],
    s: int,
    records: Sequence[dict],
    max_head: int = 30,
) -> dict:
    counts = multiset_counts(A_cols)
    multiplicity_hist = Counter(counts.values())
    distinct_fast = all(v == 1 for v in counts.values())
    support_bitset = 0
    for p in counts:
        support_bitset |= 1 << (p - 1)

    t0 = time.time()
    by_dim = Counter()
    by_L = Counter()
    by_excess = Counter()
    by_occ_cap = Counter()
    max_excess = 0
    violation_count = 0
    head: List[dict] = []

    for rec in records:
        if distinct_fast:
            occ = (int(rec["point_bitset"]) & support_bitset).bit_count()
        else:
            bs = int(rec["point_bitset"])
            occ = sum(c for p, c in counts.items() if (bs >> (p - 1)) & 1)
        cap = int(s) - int(rec["L"])
        if occ > cap:
            excess = occ - cap
            violation_count += 1
            max_excess = max(max_excess, excess)
            by_dim[rec["dim8"]] += 1
            by_L[rec["L"]] += 1
            by_excess[excess] += 1
            by_occ_cap[(occ, cap)] += 1
            if max_head > 0 and (len(head) < max_head or excess > min(h["excess"] for h in head)):
                item = {
                    "key8": rec["key8"],
                    "basis8": list(unpack_basis(rec["key8"])),
                    "key9": rec["key9"],
                    "basis9": list(unpack_basis(rec["key9"])),
                    "dim8": rec["dim8"],
                    "dim9": rec["dim9"],
                    "L": rec["L"],
                    "cap": cap,
                    "occupancy": occ,
                    "excess": excess,
                    "point_count": rec["point_count"],
                }
                head.append(item)
                head.sort(key=lambda x: (x["excess"], x["L"], x["occupancy"], x["dim8"]), reverse=True)
                head = head[:max_head]

    return {
        "label": label,
        "rank_s": int(s),
        "term_count_with_multiplicity": len(A_cols),
        "distinct_A_points": len(counts),
        "A_multiplicity_hist": {str(k): v for k, v in sorted(multiplicity_hist.items())},
        "complete_constraint_count": len(records),
        "complete_violation_count": violation_count,
        "max_excess": max_excess,
        "violations_by_dim8": {str(k): v for k, v in sorted(by_dim.items())},
        "violations_by_full_lut_L": {str(k): v for k, v in sorted(by_L.items())},
        "violations_by_excess": {str(k): v for k, v in sorted(by_excess.items())},
        "violations_by_occ_cap_head": {str(k): v for k, v in sorted(by_occ_cap.items())[:40]},
        "violations_head": head,
        "elapsed_sec": round(time.time() - t0, 3),
    }


def saturation_domains(T: np.ndarray, A_cols: Sequence[int]) -> dict:
    """Compute all saturated contractions and term-wise saturated domains."""
    na, nb, nc = T.shape
    nterms = len(A_cols)
    sat_B: List[List[Tuple[int, ...]]] = [[] for _ in range(nterms)]
    sat_C: List[List[Tuple[int, ...]]] = [[] for _ in range(nterms)]
    sat_records = []
    undersaturated = []
    q_rank_hist = Counter()
    count_minus_rank_hist = Counter()

    for q in range(1, 1 << na):
        I = [s for s, a in enumerate(A_cols) if ((int(q) & int(a)).bit_count() & 1)]
        cnt = len(I)
        M = contraction_matrix(T, q)
        rk = mat_rank_f2(M)
        q_rank_hist[rk] += 1
        count_minus_rank_hist[cnt - rk] += 1
        if cnt < rk:
            undersaturated.append({
                "q": q,
                "q_hex": hex(q),
                "rank": rk,
                "count": cnt,
                "defect": rk - cnt,
                "terms": I,
            })
        elif cnt == rk and cnt > 0:
            Bb = col_space_basis(M)
            Cb = row_space_basis(M)
            rec = {
                "q": q,
                "q_hex": hex(q),
                "rank": rk,
                "count": cnt,
                "terms": I,
                "B_space_dim": len(Bb),
                "C_space_dim": len(Cb),
                "B_space_basis": list(Bb),
                "C_space_basis": list(Cb),
            }
            sat_records.append(rec)
            for s in I:
                sat_B[s].append(Bb)
                sat_C[s].append(Cb)

    B_domains = [intersection_basis(sat_B[s], nb) for s in range(nterms)]
    C_domains = [intersection_basis(sat_C[s], nc) for s in range(nterms)]
    term_summaries = []
    for s, a in enumerate(A_cols):
        term_summaries.append({
            "term": s,
            "a": int(a),
            "a_hex": hex(int(a)),
            "sat_contractions": len(sat_B[s]),
            "B_dim": len(B_domains[s]),
            "C_dim": len(C_domains[s]),
            "linear_X_dim": len(B_domains[s]) * len(C_domains[s]),
            "B_basis": list(B_domains[s]),
            "C_basis": list(C_domains[s]),
        })
    lin = linear_membership_test(T, A_cols, B_domains, C_domains)
    return {
        "B_domains": B_domains,
        "C_domains": C_domains,
        "sat_records": sat_records,
        "undersaturated": undersaturated,
        "term_summaries": term_summaries,
        "summary": {
            "q_rank_hist": {str(k): v for k, v in sorted(q_rank_hist.items())},
            "count_minus_rank_hist": {str(k): v for k, v in sorted(count_minus_rank_hist.items())},
            "undersaturated_contraction_count": len(undersaturated),
            "saturated_contraction_count": len(sat_records),
            "saturated_by_rank": {str(k): v for k, v in sorted(Counter(r["rank"] for r in sat_records).items())},
            "term_domain_dims_hist": {f"B{k[0]}_C{k[1]}": v for k, v in sorted(Counter((len(B_domains[s]), len(C_domains[s])) for s in range(nterms)).items())},
            "zero_domain_terms": [t for t in term_summaries if t["B_dim"] == 0 or t["C_dim"] == 0],
            "linear_membership": lin,
        },
    }


def sum_space_dim(domain_list: Sequence[Sequence[int]], n: int) -> int:
    rows = []
    for basis in domain_list:
        rows.extend(int(b) for b in basis)
    return gf2_rank_rows(rows, n)


def transversal_failures(
    sat_records: Sequence[dict],
    B_domains: Sequence[Sequence[int]],
    C_domains: Sequence[Sequence[int]],
    nB: int,
    nC: int,
    max_report: int = 60,
) -> dict:
    failures = []
    per_q_first = []
    for rec in sat_records:
        I = [int(x) for x in rec["terms"]]
        m = len(I)
        q_failures = []
        if m <= 1:
            continue
        # Enumerate subsets by increasing cardinality to expose short witnesses.
        for side, domains, n in (("B", B_domains, nB), ("C", C_domains, nC)):
            side_first: Optional[dict] = None
            for size in range(1, m + 1):
                for mask in range(1, 1 << m):
                    if mask.bit_count() != size:
                        continue
                    J = [I[j] for j in range(m) if (mask >> j) & 1]
                    dim = sum_space_dim([domains[s] for s in J], n)
                    if dim < size:
                        fail = {
                            "q": rec["q"],
                            "q_hex": rec["q_hex"],
                            "rank": rec["rank"],
                            "side": side,
                            "subset_terms": J,
                            "subset_size": size,
                            "sum_domain_dim": dim,
                            "term_domain_dims": [len(domains[s]) for s in J],
                            "participating_terms": I,
                        }
                        if len(failures) < max_report:
                            failures.append(fail)
                        side_first = fail
                        break
                if side_first is not None:
                    break
            if side_first is not None:
                q_failures.append(side_first)
        if q_failures:
            per_q_first.extend(q_failures[:2])
    return {
        "failure_count_reported": len(failures),
        "saturated_contractions_with_failure_reported": len({f["q"] for f in failures}),
        "failures_head": failures,
        "per_q_first_head": per_q_first[:max_report],
        "interpretation": "Any failure is a Rado independent-transversal obstruction for B or C factors inside globally intersected saturated domains. Absence of reported failures means this necessary test found no obstruction.",
    }


def actual_membership(A_cols: Sequence[int], actual_terms: Sequence[dict], B_domains, C_domains) -> dict:
    bad = []
    for s, t in enumerate(actual_terms):
        b = vec_to_mask(t["v"])
        c = vec_to_mask(t["w"])
        b_ok = in_span(b, B_domains[s], 9)
        c_ok = in_span(c, C_domains[s], 9)
        if not (b_ok and c_ok):
            bad.append({
                "term": s,
                "original_index": int(t.get("index", s)),
                "a": int(A_cols[s]),
                "b": b,
                "c": c,
                "B_dim": len(B_domains[s]),
                "C_dim": len(C_domains[s]),
                "b_ok": b_ok,
                "c_ok": c_ok,
            })
    return {"checked_terms": len(actual_terms), "all_b_c_in_domains": not bad, "bad_terms": bad[:20]}


def analyze_target(label: str, T: np.ndarray, A_cols: Sequence[int], actual_terms: Optional[Sequence[dict]] = None) -> dict:
    t0 = time.time()
    sat = saturation_domains(T, A_cols)
    trans = transversal_failures(sat["sat_records"], sat["B_domains"], sat["C_domains"], T.shape[1], T.shape[2])
    act = None
    verified = None
    if actual_terms is not None:
        verified = verify_terms(T, actual_terms)
        act = actual_membership(A_cols, actual_terms, sat["B_domains"], sat["C_domains"])
    return {
        "label": label,
        "tensor_shape": list(T.shape),
        "term_count": len(A_cols),
        "distinct_A_cols": len(set(int(a) for a in A_cols)),
        "A_multiplicity_hist": {str(k): v for k, v in sorted(Counter(Counter(int(a) for a in A_cols).values()).items())},
        "known_decomposition_verified": verified,
        "saturation_summary": sat["summary"],
        "actual_membership": act,
        "transversal_test": trans,
        "saturated_examples_head": sat["sat_records"][:12],
        "elapsed_sec": round(time.time() - t0, 3),
    }


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    t_all = time.time()

    print("Loading Wang LUT and complete core subspace table...")
    lut = load_lut()
    core = CoreQuotient(1)
    core_records, core_meta = build_core_constraints(core, lut)

    print("Loading tensors and candidate supports...")
    qmm = ROOT / "workspace/data/cn122_3x3_r23_repro/scheme.qmm"
    terms = read_qmm_terms(qmm)
    T_core = np.load(ROOT / "workspace/data/restricted_cores/mask_001_E11_core.npy").astype(np.uint8) % 2
    core_terms = restrict_terms_f2(terms, 1)
    core_A = [vec_to_mask(t["u"]) for t in core_terms]

    core = json.loads((ROOT / "workspace/data/dual_ruling/core_e11_saturation_v2.json").read_text())
    core_round_records = []
    for r in core["rounds"]:
        if r.get("status") in ("OPTIMAL", "FEASIBLE") and "support" in r:
            # Analyze all currently known rounds so partial-vs-complete behavior is visible.
            core_round_records.append(r)

    full_T = build_matmul_tensor_f2()
    combined_path = ROOT / "workspace/data/dual_ruling/combined_sep_all5.json"
    combined = json.loads(combined_path.read_text())
    rep2_support = combined["rounds"][0]["support"]

    records = []

    print("Analyzing genuine cn122 E11-core positive control (21 surviving terms, multiplicities retained)...")
    pos_sat = analyze_target("validation_E11_core_cn122_genuine_rank21", T_core, core_A, core_terms)
    pos_scan = complete_core_wang_scan("validation_E11_core_cn122_genuine_rank21", core_A, len(core_A), core_records)
    records.append({"kind": "positive_control", "saturation_and_transversal": pos_sat, "complete_core_wang_scan": pos_scan})
    print(json.dumps({
        "label": pos_sat["label"],
        "terms": pos_sat["term_count"],
        "distinct_A": pos_sat["distinct_A_cols"],
        "verified": pos_sat["known_decomposition_verified"],
        "complete_violations": pos_scan["complete_violation_count"],
        "linear": pos_sat["saturation_summary"]["linear_membership"]["necessary_linear_test_passed"],
        "zero_terms": len(pos_sat["saturation_summary"]["zero_domain_terms"]),
        "transversal_failures": pos_sat["transversal_test"]["failure_count_reported"],
    }, sort_keys=True))

    print("Analyzing analysis E11-core candidate rounds against the complete core table and transversal test...")
    for r in core_round_records:
        label = f"core_round{r['round']}_partialscan"
        A = [int(x) for x in r["support"]]
        sat_res = analyze_target(label, T_core, A, None)
        scan = complete_core_wang_scan(label, A, 19, core_records)
        records.append({
            "kind": "core_candidate_round",
            "round_record": r,
            "saturation_and_transversal": sat_res,
            "complete_core_wang_scan": scan,
            "partial_scan_warning": "analysis wang_violations counted only spans generated by <=5 selected points. complete_core_wang_scan is authoritative for Wang admissibility of this fixed A multiset.",
        })
        print(json.dumps({
            "label": label,
            "partial_violations": r.get("wang_violations"),
            "complete_violations": scan["complete_violation_count"],
            "max_excess": scan["max_excess"],
            "zero_terms": len(sat_res["saturation_summary"]["zero_domain_terms"]),
            "linear": sat_res["saturation_summary"]["linear_membership"]["necessary_linear_test_passed"],
            "affine_dim": sat_res["saturation_summary"]["linear_membership"]["affine_solution_dimension_if_consistent"],
            "transversal_failures": sat_res["transversal_test"]["failure_count_reported"],
        }, sort_keys=True))

    print("Analyzing analysis combined rep2 support for collective saturation independence...")
    rep2_sat = analyze_target("combined_rep2_all5_round0", full_T, [int(x) for x in rep2_support], None)
    records.append({
        "kind": "rep2_combined_support",
        "source": str(combined_path),
        "source_round_record": combined["rounds"][0],
        "saturation_and_transversal": rep2_sat,
    })
    print(json.dumps({
        "label": rep2_sat["label"],
        "saturated": rep2_sat["saturation_summary"]["saturated_contraction_count"],
        "zero_terms": len(rep2_sat["saturation_summary"]["zero_domain_terms"]),
        "linear": rep2_sat["saturation_summary"]["linear_membership"]["necessary_linear_test_passed"],
        "affine_dim": rep2_sat["saturation_summary"]["linear_membership"]["affine_solution_dimension_if_consistent"],
        "transversal_failures": rep2_sat["transversal_test"]["failure_count_reported"],
    }, sort_keys=True))

    result = {
        "schema": "core_complete_transversal_v1",
        "field": "F2",
        "purpose": "Correct analysis core-support interpretation with complete Wang scanning, genuine cn122 core positive control, multiplicity-aware occupancy, and saturated-domain independent-transversal tests.",
        "core_table_meta": core_meta,
        "records": records,
        "global_corrections": [
            "analysis core_e11_saturation_v2 partial wang_violations are not complete Wang-admissibility counts; complete_core_wang_scan must be used before interpreting a core A-support as Wang-admissible.",
            "analysis Boolean core search uses distinct A-points; rank-19 decompositions with repeated projected A-directions remain possible unless multiplicity is separately excluded.",
            "The correct cn122 E11-core positive control has 21 surviving restricted terms after quotienting all 23 terms and discarding only zero projected A-factors; multiplicities are retained.",
            "Saturation compatibility includes Rado independent-transversal conditions for B and C domains on every saturated contraction, not only nonzero individual domains or linear tensor membership.",
        ],
        "total_elapsed_sec": round(time.time() - t_all, 3),
    }
    out = OUTDIR / "analysis.json"
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(f"Saved {out}")


if __name__ == "__main__":
    main()
