#!/usr/bin/env python3
"""Enhanced lazy solver for Wang T-level occupation capacity over F2.

This is a stronger execution driver around the complete LUT generated by
wang_capacity_lazy.py.  It supports
  * adding all subspace constraints up to an initial dimension (usually 3),
  * adding all or a capped number of violated subset-span cuts per iteration,
  * optional symmetry-breaking branches by the rank type of one selected A-factor.

The mathematical problem for rank s is the same necessary condition:
    choose s projective points in F2^9 such that
    |support ∩ Phi| <= s - L(Phi) for every Wang subspace Phi.
For s=20, infeasibility of the complete system would prove R_F2(T333) >= 21.
"""
from __future__ import annotations

import argparse
import json
import pickle
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from wang_capacity_lazy import (  # noqa: E402
    unpack_basis,
    subspace_points_from_basis,
    in_rowspace,
    all_subset_span_keys,
    occupancy_of_key,
    matrix_rank_of_mask,
)

CANON_BY_RANK = {1: 1, 2: 1 | 16, 3: 1 | 16 | 256}


def load_lut(path: Path) -> Tuple[Dict[int, int], dict]:
    with path.open("rb") as f:
        payload = pickle.load(f)
    return payload["lut"], payload.get("meta", {})


def find_violations(solution: Dict[int, int], s: int, lut: Dict[int, int], max_cuts: int = 0) -> Tuple[List[dict], dict]:
    support = sorted(solution)
    t0 = time.time()
    keys = all_subset_span_keys(support)
    violations = []
    for key in keys:
        lb = lut.get(key)
        if lb is None:
            raise KeyError(f"span key missing from complete LUT: {key}")
        occ = occupancy_of_key(key, solution)
        cap = s - lb
        if occ > cap:
            violations.append({
                "key": key,
                "dim": key & 0xF,
                "basis": list(unpack_basis(key)),
                "lb": lb,
                "cap": cap,
                "occupancy": occ,
                "excess": occ - cap,
            })
    violations.sort(key=lambda v: (v["excess"], v["lb"], v["occupancy"], -v["dim"]), reverse=True)
    stats = {
        "support_size": len(support),
        "total_multiplicity": sum(solution.values()),
        "unique_subset_spans": len(keys),
        "violation_count": len(violations),
        "violations_by_dim": dict(Counter(v["dim"] for v in violations)),
        "violations_by_lb": dict(Counter(v["lb"] for v in violations)),
        "elapsed_sec": time.time() - t0,
    }
    if max_cuts and len(violations) > max_cuts:
        return violations[:max_cuts], stats
    return violations, stats


def solve(lut: Dict[int, int], s: int, outdir: Path, label: str, init_max_dim: int = 2,
          max_iters: int = 100, solver_time: float = 300.0, max_cuts_per_iter: int = 0,
          branch_rank: int = 0) -> dict:
    from ortools.sat.python import cp_model

    model = cp_model.CpModel()
    points = list(range(1, 512))
    x = {p: model.NewIntVar(0, s, f"x_{p}") for p in points}
    model.Add(sum(x[p] for p in points) == s)

    if branch_rank:
        canon = CANON_BY_RANK[branch_rank]
        model.Add(x[canon] >= 1)
        if branch_rank >= 2:
            for p in points:
                if matrix_rank_of_mask(p) < branch_rank:
                    model.Add(x[p] == 0)
        print(f"Symmetry branch rank={branch_rank}: fixed x[{canon}]=1 and excluded lower ranks")

    added = set()
    cuts = []

    def add_cut(key: int, reason: str) -> bool:
        if key in added:
            return False
        lb = lut[key]
        cap = s - lb
        pts = subspace_points_from_basis(unpack_basis(key))
        model.Add(sum(x[p] for p in pts) <= cap)
        added.add(key)
        cuts.append({"key": key, "dim": key & 0xF, "lb": lb, "cap": cap, "point_count": len(pts), "reason": reason})
        return True

    t0 = time.time()
    for key in sorted(lut):
        d = key & 0xF
        if 1 <= d <= init_max_dim:
            add_cut(key, f"all_dim_le_{init_max_dim}_initial")
    print(f"Initial cuts dim<= {init_max_dim}: {len(added):,} in {time.time()-t0:.2f}s by dim {dict(Counter(c['dim'] for c in cuts))}")

    history = []
    final_status = None
    final_solution = None
    for it in range(1, max_iters + 1):
        solver = cp_model.CpSolver()
        solver.parameters.max_time_in_seconds = solver_time
        solver.parameters.num_search_workers = 8
        solver.parameters.random_seed = 7000 + it
        st0 = time.time()
        status = solver.Solve(model)
        selapsed = time.time() - st0
        status_name = {
            cp_model.OPTIMAL: "OPTIMAL",
            cp_model.FEASIBLE: "FEASIBLE",
            cp_model.INFEASIBLE: "INFEASIBLE",
            cp_model.MODEL_INVALID: "MODEL_INVALID",
            cp_model.UNKNOWN: "UNKNOWN",
        }.get(status, str(status))
        entry = {"iteration": it, "solver_status": status_name, "cut_count": len(added), "solve_elapsed_sec": selapsed}
        print(f"[{label}] iter {it}: status={status_name}, cuts={len(added):,}, solve={selapsed:.2f}s")
        if status in (cp_model.INFEASIBLE, cp_model.MODEL_INVALID):
            final_status = status_name
            history.append(entry)
            break
        if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            final_status = status_name
            history.append(entry)
            break
        sol = {p: solver.Value(v) for p, v in x.items() if solver.Value(v)}
        entry["solution"] = {str(k): v for k, v in sorted(sol.items())}
        entry["support_size"] = len(sol)
        entry["max_mult"] = max(sol.values()) if sol else 0
        entry["rank_count"] = dict(Counter(matrix_rank_of_mask(p) for p in sol for _ in range(sol[p])))
        violations, stats = find_violations(sol, s, lut, max_cuts=max_cuts_per_iter)
        entry["check_stats"] = stats
        entry["violations_head"] = violations[:50]
        print(f"  support={len(sol)}, maxmult={entry['max_mult']}, ranks={entry['rank_count']}, spans={stats['unique_subset_spans']:,}, violations={stats['violation_count']:,}, added_candidates={len(violations):,}, check={stats['elapsed_sec']:.2f}s")
        if not violations:
            final_status = "CAPACITY_FEASIBLE_NO_VIOLATION_FOUND"
            final_solution = sol
            history.append(entry)
            break
        nadd = 0
        for v in violations:
            if add_cut(v["key"], f"lazy_iter_{it}"):
                nadd += 1
        entry["lazy_cuts_added"] = nadd
        print(f"  added {nadd:,} lazy cuts")
        history.append(entry)
        if nadd == 0:
            final_status = "STALLED_NO_NEW_CUTS"
            final_solution = sol
            break

    result = {
        "problem": "T-level Wang occupation capacity enhanced",
        "field": "F2",
        "rank_s": s,
        "label": label,
        "init_max_dim": init_max_dim,
        "max_cuts_per_iter": max_cuts_per_iter,
        "branch_rank": branch_rank,
        "branch_meaning": "branch_rank=1: selected support contains a rank-1 point; branch_rank=2: no rank-1 points and a rank-2 point fixed; branch_rank=3: all selected points rank 3 with identity fixed" if branch_rank else "unbranched",
        "final_status": final_status,
        "final_solution": {str(k): v for k, v in sorted(final_solution.items())} if final_solution else None,
        "iterations": history,
        "cut_count": len(added),
        "cuts_by_dim": dict(Counter(c["dim"] for c in cuts)),
        "cuts_by_lb": dict(Counter(c["lb"] for c in cuts)),
        "cut_records_head": cuts[:100],
        "cut_records_tail": cuts[-100:],
    }
    outdir.mkdir(parents=True, exist_ok=True)
    outpath = outdir / f"enhanced_{label}.json"
    outpath.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(f"Saved {outpath}")
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lut", type=Path, default=Path("data/wang_f2_lb20/wang_subspace_lut.pkl"))
    ap.add_argument("--outdir", type=Path, default=Path("data/wang_capacity"))
    ap.add_argument("--rank", type=int, default=20)
    ap.add_argument("--label", default="s20_enhanced")
    ap.add_argument("--init-max-dim", type=int, default=3)
    ap.add_argument("--max-iters", type=int, default=100)
    ap.add_argument("--solver-time", type=float, default=300.0)
    ap.add_argument("--max-cuts-per-iter", type=int, default=0, help="0 means add all violated subset-span cuts")
    ap.add_argument("--branch-rank", type=int, choices=[0,1,2,3], default=0)
    args = ap.parse_args()
    lut, meta = load_lut(args.lut)
    print(f"Loaded LUT {len(lut):,}; coverage_ok={meta.get('coverage_ok')}; conflicts={meta.get('conflict_count')}")
    solve(lut, args.rank, args.outdir, args.label, init_max_dim=args.init_max_dim,
          max_iters=args.max_iters, solver_time=args.solver_time,
          max_cuts_per_iter=args.max_cuts_per_iter, branch_rank=args.branch_rank)

if __name__ == "__main__":
    main()
