#!/usr/bin/env python3
"""analysis: Check whether known rank-23 schemes have tau-type automorphisms
up to sandwich conjugacy (not just literal tau-fixedness).

From Burichenko (1508.01110): Aut(Laderman) = S4, generated by:
  Phi1 = T(pi23, pi13, 1)           [factor-preserving]
  Phi2 = T(pi23, 1, pi23)           [factor-preserving]
  Phi3(x,y,z) = (y^T eps2, eps2 x^T, z^T)  [uses rho_(12)]
  Phi4(x,y,z) = (eps1 z pi12, pi12 x pi12 eps1, eps1 pi12 y eps1)  [uses rho_(123)]

Our tau = rho_(23): (x,y,z) -> (x^T, z^T, y^T).
rho_(23) = rho_(123) * rho_(12) in S3, so the S4 automorphism group
contains a rho_(23)-type element. That element is Phi4 * Phi3 (or similar).

This script:
1. Reconstructs Laderman's algorithm in Burichenko's convention
2. Tests all S4 generators and products for tau-type action
3. Identifies the exact tau-type automorphism
"""
import numpy as np
from pathlib import Path
import json

SCRIPT_DIR = Path(__file__).resolve().parent
WS = SCRIPT_DIR.parent
DATA_DIR = WS / "data" / "laderman_tau"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Special matrices
pi12 = np.array([[0,1,0],[1,0,0],[0,0,1]], dtype=int)
pi13 = np.array([[0,0,1],[0,1,0],[1,0,0]], dtype=int)
pi23 = np.array([[1,0,0],[0,0,1],[0,1,0]], dtype=int)
eps1 = np.diag([-1,1,1])
eps2 = np.diag([1,-1,1])
eps3 = np.diag([1,1,-1])
I3 = np.eye(3, dtype=int)

def T_action(a, b, c, x, y, z):
    """T(a,b,c)(x,y,z) = (a x b^{-1}, b y c^{-1}, c z a^{-1})"""
    bi = np.linalg.inv(b).astype(int) if np.abs(np.linalg.det(b)) == 1 else np.linalg.inv(b)
    ci = np.linalg.inv(c).astype(int) if np.abs(np.linalg.det(c)) == 1 else np.linalg.inv(c)
    ai = np.linalg.inv(a).astype(int) if np.abs(np.linalg.det(a)) == 1 else np.linalg.inv(a)
    return (a @ x @ bi, b @ y @ ci, c @ z @ ai)

def Phi1(x, y, z):
    return T_action(pi23, pi13, I3, x, y, z)

def Phi2(x, y, z):
    return T_action(pi23, I3, pi23, x, y, z)

def Phi3(x, y, z):
    return (y.T @ eps2, eps2 @ x.T, z.T)

def Phi4(x, y, z):
    return (eps1 @ z @ pi12, pi12 @ x @ pi12 @ eps1, eps1 @ pi12 @ y @ eps1)

def tau_standard(x, y, z):
    """Standard tau: (x,y,z) -> (x^T, z^T, y^T)"""
    return (x.T, z.T, y.T)

def compose(f, g):
    """Compose automorphisms: (f∘g)(x,y,z) = f(g(x,y,z))"""
    def h(x, y, z):
        x1, y1, z1 = g(x, y, z)
        return f(x1, y1, z1)
    return h

def check_tau_type(phi, label=""):
    """Check if phi acts as a tau-type permutation (swapping factors 2,3)."""
    # Test on random integer triples
    np.random.seed(42)
    is_tau = True
    for _ in range(5):
        x = np.random.randint(-3, 4, (3,3))
        y = np.random.randint(-3, 4, (3,3))
        z = np.random.randint(-3, 4, (3,3))
        x1, y1, z1 = phi(x, y, z)
        # Tau-type: x1 depends on x only (and is linear), y1 depends on z, z1 depends on y
        # Test: if we change y only, does x1 change? (Should not for tau-type)
        y2 = np.random.randint(-3, 4, (3,3))
        x1b, _, _ = phi(x, y2, z)
        if not np.allclose(x1, x1b):
            is_tau = False
            break
        # If we change z only, does y1 change? (Should for tau-type)
        z2 = np.random.randint(-3, 4, (3,3))
        _, y1b, _ = phi(x, y, z2)
        if np.allclose(y1, y1b) and not np.allclose(z, z2):
            is_tau = False
            break
    return is_tau

# Test all generators and their products
generators = {
    'Phi1': Phi1, 'Phi2': Phi2, 'Phi3': Phi3, 'Phi4': Phi4,
    'tau': tau_standard
}

products_to_test = {
    'Phi4*Phi3': compose(Phi4, Phi3),
    'Phi3*Phi4': compose(Phi3, Phi4),
    'Phi4^2*Phi3': compose(Phi4, compose(Phi4, Phi3)),
    'Phi3*Phi4^2': compose(Phi3, compose(Phi4, Phi4)),
    'Phi1*Phi3': compose(Phi1, Phi3),
    'Phi2*Phi3': compose(Phi2, Phi3),
    'Phi1*Phi4*Phi3': compose(Phi1, compose(Phi4, Phi3)),
    'Phi2*Phi4*Phi3': compose(Phi2, compose(Phi4, Phi3)),
    'Phi1*Phi2*Phi4*Phi3': compose(Phi1, compose(Phi2, compose(Phi4, Phi3))),
    'Phi4^2*Phi3*Phi1': compose(compose(Phi4, Phi4), compose(Phi3, Phi1)),
    'Phi4^2*Phi3*Phi2': compose(compose(Phi4, Phi4), compose(Phi3, Phi2)),
}

results = {"generators": {}, "products": {}}

print("=== Testing generators ===")
for name, phi in generators.items():
    is_tau = check_tau_type(phi, name)
    results["generators"][name] = {"is_tau_type": is_tau}
    print(f"  {name}: tau-type={is_tau}")

print("\n=== Testing products for tau-type (rho_23) ===")
tau_type_found = []
for name, phi in products_to_test.items():
    is_tau = check_tau_type(phi, name)
    results["products"][name] = {"is_tau_type": is_tau}
    if is_tau:
        tau_type_found.append(name)
    print(f"  {name}: tau-type={is_tau}")

print(f"\nTau-type elements found: {tau_type_found}")

# For each tau-type element, extract the T(a,b,c) part
# tau-type means phi(x,y,z) = (A x B^{-1}, C z D^{-1}, E y F^{-1}) for some matrices
# i.e. = T(A, B', C') * rho_(23) where rho_(23)(x,y,z) = (x^T, z^T, y^T)
if tau_type_found:
    name = tau_type_found[0]
    phi = products_to_test[name]
    # Extract matrices by probing with basis elements
    A_mat = np.zeros((3,3), dtype=float)
    B_mat = np.zeros((3,3), dtype=float)
    for i in range(3):
        for j in range(3):
            eij = np.zeros((3,3)); eij[i,j] = 1
            x1, _, _ = phi(eij, np.zeros((3,3)), np.zeros((3,3)))
            # x1 should be A * eij^T * B^{-1} = A * e_ji * B^{-1} 
            # which is the j-th column of A times the i-th row of B^{-1}
            pass  # complex to extract, skip for now
    
    print(f"\n=== Verifying {name} preserves T_333 ===")
    # Build T_333 = sum_{i,j,k} e_ij ⊗ e_jk ⊗ e_ki
    # Verify phi(T_333) = T_333 by checking all 729 components
    T_flat = np.zeros(729)
    for i in range(3):
        for j in range(3):
            for k in range(3):
                idx = (i*3+j)*9*9 + (j*3+k)*9 + (k*3+i)
                T_flat[idx] = 1
    
    # Apply phi term by term
    T_phi_flat = np.zeros(729)
    for i in range(3):
        for j in range(3):
            for k in range(3):
                eij = np.zeros((3,3)); eij[i,j] = 1
                ejk = np.zeros((3,3)); ejk[j,k] = 1
                eki = np.zeros((3,3)); eki[k,i] = 1
                x1, y1, z1 = phi(eij, ejk, eki)
                for a in range(3):
                    for b in range(3):
                        for c in range(3):
                            for d in range(3):
                                for e in range(3):
                                    for f in range(3):
                                        coeff = x1[a,b] * y1[c,d] * z1[e,f]
                                        idx2 = (a*3+b)*9*9 + (c*3+d)*9 + (e*3+f)
                                        T_phi_flat[idx2] += coeff
    
    match = np.allclose(T_flat, T_phi_flat)
    print(f"  {name} preserves T_333: {match}")
    results["products"][name]["preserves_T333"] = bool(match)
    
    # Test the simpler: phi^2 = id?
    np.random.seed(0)
    x = np.random.randint(-3, 4, (3,3))
    y = np.random.randint(-3, 4, (3,3))
    z = np.random.randint(-3, 4, (3,3))
    x2, y2, z2 = phi(*phi(x, y, z))
    is_invol = np.allclose(x, x2) and np.allclose(y, y2) and np.allclose(z, z2)
    print(f"  {name}^2 = id: {is_invol}")
    results["products"][name]["is_involution"] = bool(is_invol)

# Now load and test cn122 scheme for tau-type symmetry up to sandwich conjugacy
print("\n=== Testing cn122 for tau-type automorphism ===")
scheme_path = WS / "data" / "cn122_r23_reproduce" / "scheme.qmm"
if scheme_path.exists():
    terms = []
    with open(scheme_path) as f:
        current = {}
        for line in f:
            line = line.strip()
            if line.startswith('term '):
                if current: terms.append(current)
                current = {}
            elif line.startswith('u '):
                vals = list(map(int, line.split()[1:]))
                current['u'] = np.array(vals).reshape(3,3)
            elif line.startswith('v '):
                vals = list(map(int, line.split()[1:]))
                current['v'] = np.array(vals).reshape(3,3)
            elif line.startswith('w '):
                vals = list(map(int, line.split()[1:]))
                current['w'] = np.array(vals).reshape(3,3)
        if current: terms.append(current)
    
    # Apply tau-type element to each term and check if the resulting set
    # is a permutation of the original terms (up to scaling)
    # For the identified tau-type automorphism
    if tau_type_found:
        phi = products_to_test[tau_type_found[0]]
        transformed = []
        for t in terms:
            u1, v1, w1 = phi(t['u'], t['v'], t['w'])
            transformed.append({'u': u1, 'v': v1, 'w': w1})
        
        # Check if transformed terms match original terms up to permutation and scaling
        matched = [False] * len(terms)
        for i, tt in enumerate(transformed):
            for j, ot in enumerate(terms):
                if matched[j]: continue
                # Check if tt = lambda * ot
                for s in [1, -1]:
                    if (np.allclose(s*tt['u'], ot['u']) and 
                        np.allclose(s*tt['v'], ot['v']) and 
                        np.allclose(s*tt['w'], ot['w'])):
                        matched[j] = True
                        break
                    # Also check rank-one scaling freedom: u*alpha, v*beta, w*gamma with alpha*beta*gamma=1
                if matched[j]: break
        
        n_matched = sum(matched)
        print(f"  cn122 terms matched by {tau_type_found[0]}: {n_matched}/{len(terms)}")
        results["cn122_tau_type_match"] = n_matched
        # Note: cn122 is NOT the Laderman algorithm; it may have different symmetry

out_path = DATA_DIR / "laderman_tau_check.json"
with open(out_path, 'w') as f:
    json.dump(results, f, indent=2, default=lambda o: int(o) if isinstance(o, (np.integer,)) else float(o))
print(f"\nSAVED {out_path}")
