#!/usr/bin/env python3
"""
analysis: repair the Z4 pairing convention and validate the eigenblock pencil-conic instrument.

This script treats BILR's residual cubic C(M)=sum_{11 cubes} <L_i,M>^3
with the actual packed Euclidean pairing <L,M>=tr(L^T M).  The coefficient
cube orbit is generated by L -> a0 L a0^{-1}; therefore the variable action
preserving the residual is M -> a0^T M a0^{-T}.  We do not assume this: first
we brute-force test four natural conjugation actions on all 165 cubic coefficients.

After selecting the coefficientwise preserving action, the script builds its
eigen-coordinates over F_p (p=65521, i^2=-1), checks the invariant block split
p^3(10)+pq^2(9)+pzw(12)+qz^2(6)+qw^2(6)=43, verifies that the BILR residual has
zero coefficients outside these blocks, and runs the qz^2 pencil-conic positive
control.  The conic intersection is compared projectively with the two size-4
BILR cube-orbit z-lines; no averaging is used except as a check that Proj_inv(C)=C.
"""
from __future__ import annotations

import itertools, json
from pathlib import Path
import numpy as np

WS = Path(__file__).resolve().parent.parent
OUT = WS / "data" / "z4_pairing_pencil"
OUT.mkdir(parents=True, exist_ok=True)
P = 65521
N = 9
MONOS = list(itertools.combinations_with_replacement(range(N), 3))
MONO_IDX = {m:i for i,m in enumerate(MONOS)}


def mat_inv_mod(M, p=P):
    M = np.array(M, dtype=object) % p
    n = M.shape[0]
    aug = [[int(M[i,j]) % p for j in range(n)] + [1 if i == j else 0 for j in range(n)] for i in range(n)]
    r = 0
    for c in range(n):
        piv = None
        for i in range(r, n):
            if aug[i][c] % p:
                piv = i; break
        assert piv is not None, "singular"
        aug[r], aug[piv] = aug[piv], aug[r]
        inv = pow(aug[r][c] % p, -1, p)
        aug[r] = [(x * inv) % p for x in aug[r]]
        for i in range(n):
            if i != r and aug[i][c] % p:
                f = aug[i][c] % p
                aug[i] = [(aug[i][j] - f * aug[r][j]) % p for j in range(2*n)]
        r += 1
    R = np.zeros((n,n), dtype=object)
    for i in range(n):
        for j in range(n):
            R[i,j] = aug[i][n+j] % p
    return R


def matmul_mod(A, B, p=P):
    A = np.array(A, dtype=object) % p
    B = np.array(B, dtype=object) % p
    C = np.zeros((A.shape[0], B.shape[1]), dtype=object)
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            s = 0
            for k in range(A.shape[1]):
                s += int(A[i,k]) * int(B[k,j])
            C[i,j] = s % p
    return C


def rank_mod(A, p=P):
    A = np.array(A, dtype=object) % p
    m,n = A.shape
    B = [[int(A[i,j]) % p for j in range(n)] for i in range(m)]
    r = 0
    pivots = []
    for c in range(n):
        piv = None
        for i in range(r, m):
            if B[i][c] % p:
                piv = i; break
        if piv is None:
            continue
        B[r], B[piv] = B[piv], B[r]
        inv = pow(B[r][c] % p, -1, p)
        B[r] = [(x * inv) % p for x in B[r]]
        for i in range(m):
            if i != r and B[i][c] % p:
                f = B[i][c] % p
                B[i] = [(B[i][j] - f * B[r][j]) % p for j in range(n)]
        pivots.append(c)
        r += 1
        if r == m:
            break
    return r


def rref_basis_rows(A, p=P):
    A = np.array(A, dtype=object) % p
    m,n = A.shape
    B = [[int(A[i,j]) % p for j in range(n)] for i in range(m)]
    rows_used = []
    r = 0
    pivots = []
    for c in range(n):
        piv = None
        for i in range(r, m):
            if B[i][c] % p:
                piv = i; break
        if piv is None:
            continue
        B[r], B[piv] = B[piv], B[r]
        inv = pow(B[r][c] % p, -1, p)
        B[r] = [(x * inv) % p for x in B[r]]
        for i in range(m):
            if i != r and B[i][c] % p:
                f = B[i][c] % p
                B[i] = [(B[i][j] - f * B[r][j]) % p for j in range(n)]
        pivots.append(c)
        rows_used.append(r)
        r += 1
        if r == m:
            break
    return np.array(B[:r], dtype=object), pivots


def nullspace_mod(A, p=P):
    A = np.array(A, dtype=object) % p
    m,n = A.shape
    B = [[int(A[i,j]) % p for j in range(n)] for i in range(m)]
    pivots=[]; r=0
    for c in range(n):
        piv=None
        for i in range(r,m):
            if B[i][c] % p:
                piv=i; break
        if piv is None: continue
        B[r],B[piv]=B[piv],B[r]
        inv=pow(B[r][c]%p,-1,p)
        B[r]=[(x*inv)%p for x in B[r]]
        for i in range(m):
            if i!=r and B[i][c]%p:
                f=B[i][c]%p
                B[i]=[(B[i][j]-f*B[r][j])%p for j in range(n)]
        pivots.append(c); r+=1
    free=[c for c in range(n) if c not in pivots]
    vecs=[]
    for fc in free:
        v=[0]*n; v[fc]=1
        for row,pc in enumerate(pivots):
            v[pc]=(-B[row][fc])%p
        vecs.append(v)
    return np.array(vecs,dtype=object).T if vecs else np.zeros((n,0),dtype=object)


def eigenspace(M, ev, p=P):
    M = np.array(M, dtype=object) % p
    A = M.copy()
    for i in range(A.shape[0]):
        A[i,i] = (int(A[i,i]) - ev) % p
    return nullspace_mod(A, p)


def flatten_mat(M):
    return np.array(M, dtype=object).reshape(N)


def unflatten(v):
    return np.array(v, dtype=object).reshape(3,3)


def linear_action_matrix(left, right, p=P):
    """Row-major matrix for X -> left X right."""
    left = np.array(left, dtype=object) % p
    right = np.array(right, dtype=object) % p
    R = np.zeros((N,N), dtype=object)
    for k in range(N):
        E = np.zeros((3,3), dtype=object)
        E[k//3, k%3] = 1
        Y = matmul_mod(matmul_mod(left, E, p), right, p)
        R[:,k] = flatten_mat(Y) % p
    return R


def cube_coeffs_from_form(l, p=P):
    l = [int(x) % p for x in l]
    coeff = [0] * len(MONOS)
    for a in range(N):
        la = l[a]
        if la == 0: continue
        for b in range(N):
            lb = l[b]
            if lb == 0: continue
            for c in range(N):
                lc = l[c]
                if lc == 0: continue
                key = tuple(sorted((a,b,c)))
                coeff[MONO_IDX[key]] = (coeff[MONO_IDX[key]] + la*lb*lc) % p
    return np.array(coeff, dtype=object)


def prod3_coeffs(l1, l2, l3, p=P, factor=1):
    l1=[int(x)%p for x in l1]; l2=[int(x)%p for x in l2]; l3=[int(x)%p for x in l3]
    coeff=[0]*len(MONOS)
    for a in range(N):
        if l1[a]==0: continue
        for b in range(N):
            if l2[b]==0: continue
            for c in range(N):
                if l3[c]==0: continue
                key=tuple(sorted((a,b,c)))
                coeff[MONO_IDX[key]]=(coeff[MONO_IDX[key]] + factor*l1[a]*l2[b]*l3[c])%p
    return np.array(coeff,dtype=object)


def sum_cube_coeffs(forms, p=P):
    total = np.zeros(len(MONOS), dtype=object)
    for l in forms:
        total = (total + cube_coeffs_from_form(l, p)) % p
    return total


def target_trX3_coeffs_in_basis(change, p=P):
    """tr(X^3) in coordinates y where old row-major variables x = change y."""
    total = np.zeros(len(MONOS), dtype=object)
    for a,b,c in itertools.product(range(3), repeat=3):
        r1 = 3*a + b
        r2 = 3*b + c
        r3 = 3*c + a
        total = (total + prod3_coeffs(change[r1,:], change[r2,:], change[r3,:], p)) % p
    return total


def free_contribution_in_basis(Tcols_y, Ddiag, p=P):
    """3 * sum_{k=0}^3 l_A,k l_B,k l_C,k in y coordinates."""
    total = np.zeros(len(MONOS), dtype=object)
    A = np.array(Tcols_y[:,0], dtype=object) % p
    B = np.array(Tcols_y[:,1], dtype=object) % p
    C = np.array(Tcols_y[:,2], dtype=object) % p
    Ddiag = [int(x)%p for x in Ddiag]
    for k in range(4):
        scales = np.array([pow(d,k,p) for d in Ddiag], dtype=object)
        Ak = (A * scales) % p
        Bk = (B * scales) % p
        Ck = (C * scales) % p
        total = (total + prod3_coeffs(Ak,Bk,Ck,p,factor=3)) % p
    return total


def coeff_transform_under_variable_action(coeff, R, p=P):
    """Return coefficients of f(R x) for a polynomial represented as sum of monomial coeffs.
    Implemented by expanding each old monomial using rows of R.
    """
    total=np.zeros(len(MONOS),dtype=object)
    for idx,(a,b,c) in enumerate(MONOS):
        val=int(coeff[idx])%p
        if val==0: continue
        total=(total + prod3_coeffs(R[a,:], R[b,:], R[c,:], p, factor=val))%p
    return total


def scalar_projective_match(v, w, p=P):
    v=[int(x)%p for x in v]; w=[int(x)%p for x in w]
    if all(x==0 for x in v) or all(x==0 for x in w):
        return all(x==0 for x in v) and all(x==0 for x in w), 0
    lam=None
    for a,b in zip(v,w):
        if b%p:
            lam=(a*pow(b,-1,p))%p
            break
    assert lam is not None
    return all((a-lam*b)%p==0 for a,b in zip(v,w)), lam


def mat3_to_list(M):
    return [[int(M[i,j]) for j in range(M.shape[1])] for i in range(M.shape[0])]


def vec_to_list(v):
    return [int(x) for x in list(v)]


# Load exact BILR data.
sch = json.loads((WS/"data"/"ballard_z4_cyclic"/"ballard_z4_cyclic_scheme.json").read_text())
cubes = [np.array(c, dtype=object).reshape(3,3) for c in sch["cubes"]]
cubes_flat = [flatten_mat(C) % P for C in cubes]
U0 = np.array(sch["free_orbit_representatives"][0]["U"], dtype=object).reshape(3,3)
V0 = np.array(sch["free_orbit_representatives"][0]["V"], dtype=object).reshape(3,3)
W0 = np.array(sch["free_orbit_representatives"][0]["W"], dtype=object).reshape(3,3)
Tcols_old = np.stack([flatten_mat(U0), flatten_mat(V0), flatten_mat(W0)], axis=1) % P

a0 = np.array([[0,0,-1],[1,0,-1],[0,1,-1]], dtype=object) % P
a0i = mat_inv_mod(a0, P)
a0T = a0.T % P
a0mT = mat_inv_mod(a0T, P)  # a0^{-T}

residual_old = sum_cube_coeffs(cubes_flat, P)
# target in old basis and free contribution in old basis for anchor.
change_old = np.eye(N, dtype=object)
target_old = target_trX3_coeffs_in_basis(change_old, P)
# Coefficient action G = L -> a0 L a0^{-1}; its matrix equals R_pair^T for R_pair below.
G_coeff = linear_action_matrix(a0, a0i, P)
G_pows = [np.eye(N, dtype=object)]
for _ in range(3):
    G_pows.append(matmul_mod(G_coeff, G_pows[-1], P))
free_old = np.zeros(len(MONOS), dtype=object)
A0,B0,C0 = Tcols_old[:,0], Tcols_old[:,1], Tcols_old[:,2]
for k in range(4):
    Ak = matmul_mod(G_pows[k], A0.reshape(N,1), P).reshape(N)
    Bk = matmul_mod(G_pows[k], B0.reshape(N,1), P).reshape(N)
    Ck = matmul_mod(G_pows[k], C0.reshape(N,1), P).reshape(N)
    free_old = (free_old + prod3_coeffs(Ak,Bk,Ck,P,factor=3)) % P
anchor_diff = (target_old - free_old - residual_old) % P

# Candidate variable actions for brute-force coefficient invariance.
actions = {
    "Ad_a0__X_to_a0_X_a0inv": linear_action_matrix(a0, a0i, P),
    "Ad_a0inv__X_to_a0inv_X_a0": linear_action_matrix(a0i, a0, P),
    "pairing_rho__X_to_a0T_X_a0minusT": linear_action_matrix(a0T, a0mT, P),
    "pairing_rho_inv__X_to_a0minusT_X_a0T": linear_action_matrix(a0mT, a0T, P),
}

action_records=[]
for name,R in actions.items():
    # f(R x) for residual and trX3.
    res_R = sum_cube_coeffs([matmul_mod(R.T, c.reshape(N,1), P).reshape(N) for c in cubes_flat], P)
    target_R = coeff_transform_under_variable_action(target_old, R, P)
    diff_res = (res_R - residual_old) % P
    diff_target = (target_R - target_old) % P

    # Termwise cube-set action under coefficient transform R^T, allowing scalar lambda with lambda^3=1.
    used_counts=[]; maps=[]; all_found=True
    roots3=[x for x in range(P) if pow(x,3,P)==1]
    # P has 3 cube roots; enumerate once cheaply because P is small enough but store concise.
    for ci,c in enumerate(cubes_flat):
        c2 = matmul_mod(R.T, c.reshape(N,1), P).reshape(N)
        found=[]
        for j,d in enumerate(cubes_flat):
            ok, lam = scalar_projective_match(c2, d, P)
            if ok and pow(lam,3,P)==1:
                found.append((j,lam))
        if not found:
            all_found=False
        maps.append({"from":ci,"to_lam": [(int(j), int(lam)) for j,lam in found[:4]]})
    action_records.append({
        "name": name,
        "residual_diff_nonzero": int(sum(1 for x in diff_res if int(x)%P)),
        "target_diff_nonzero": int(sum(1 for x in diff_target if int(x)%P)),
        "cube_set_projectively_preserved_with_lambda3_1": bool(all_found),
        "first_maps": maps[:11],
        "matrix_rank_R_minus_I": int(rank_mod((R - np.eye(N,dtype=object))%P, P)),
    })

# Select the pairing action and build eigenbasis.
R = actions["pairing_rho__X_to_a0T_X_a0minusT"]
# Check R^T is coefficient conjugation by a0.
Rt_minus_G = (R.T - G_coeff) % P
Rt_equals_G = int(sum(1 for x in Rt_minus_G.reshape(-1) if int(x)%P)) == 0

# sqrt(-1)
imag = None
for a in range(2,P):
    if (a*a)%P == P-1:
        imag = a; break
assert imag is not None
# prefer deterministic sqrt used by search? any sqrt is fine.
# If first sqrt not found by direct square until maybe 256; p small enough.

eval_order = [("p",1,0), ("q",P-1,2), ("z",imag,1), ("w",P-imag,3)]
eig_blocks=[]; dims={}; exponents=[]
for label,ev,exp in eval_order:
    E = eigenspace(R, ev, P)
    eig_blocks.append(E)
    dims[label]=int(E.shape[1])
    exponents += [exp]*E.shape[1]
change = np.hstack(eig_blocks) % P
change_rank = rank_mod(change, P)
change_inv = mat_inv_mod(change, P)
# Verify R*change = change*D.
Ddiag=[]
for label,ev,exp in eval_order:
    Ddiag += [ev]*dims[label]
Dmat = np.diag(np.array(Ddiag, dtype=object))
eig_resid = (matmul_mod(R, change, P) - matmul_mod(change, Dmat, P)) % P
eig_resid_nz = int(sum(1 for x in eig_resid.reshape(-1) if int(x)%P))

# Blocks of invariant monomials.
def label_of_var(i):
    if i < dims['p']:
        return 'p'
    if i < dims['p'] + dims['q']:
        return 'q'
    if i < dims['p'] + dims['q'] + dims['z']:
        return 'z'
    return 'w'

def exp_of_var(i):
    return exponents[i]

def block_name(m):
    counts={"p":0,"q":0,"z":0,"w":0}
    e=0
    for i in m:
        counts[label_of_var(i)] += 1
        e = (e + exp_of_var(i)) % 4
    if e != 0:
        return None
    if counts == {"p":3,"q":0,"z":0,"w":0}: return "p3"
    if counts == {"p":1,"q":2,"z":0,"w":0}: return "pq2"
    if counts == {"p":1,"q":0,"z":1,"w":1}: return "pzw"
    if counts == {"p":0,"q":1,"z":2,"w":0}: return "qz2"
    if counts == {"p":0,"q":1,"z":0,"w":2}: return "qw2"
    return "other_invariant"

block_idx={k:[] for k in ["p3","pq2","pzw","qz2","qw2","other_invariant"]}
noninv_idx=[]
for i,m in enumerate(MONOS):
    b=block_name(m)
    if b is None: noninv_idx.append(i)
    else: block_idx[b].append(i)

# Form transformation to y coordinates: old x = change*y, so l_y = change^T l_old.
def form_to_y(l_old):
    return matmul_mod(change.T, np.array(l_old,dtype=object).reshape(N,1), P).reshape(N)

forms_y=[form_to_y(c) for c in cubes_flat]
residual_y = sum_cube_coeffs(forms_y, P)
target_y = target_trX3_coeffs_in_basis(change, P)
Tcols_y = matmul_mod(change.T, Tcols_old, P)
free_y = free_contribution_in_basis(Tcols_y, Ddiag, P)
y_anchor_diff = (target_y - free_y - residual_y) % P

noninv_nonzero = int(sum(1 for i in noninv_idx if int(residual_y[i])%P))
other_inv_nonzero = int(sum(1 for i in block_idx["other_invariant"] if int(residual_y[i])%P))
block_nonzero={bn:int(sum(1 for i in idxs if int(residual_y[i])%P)) for bn,idxs in block_idx.items()}
block_dims={bn:int(len(idxs)) for bn,idxs in block_idx.items()}

# Projection diagnostic: set non-invariant entries to zero; should not change C.
proj_diff_nz = noninv_nonzero

# Group cubes under preserving coefficient action G = R^T.
def find_exact_cube(v):
    for j,d in enumerate(cubes_flat):
        if all((int(v[k]) - int(d[k]))%P == 0 for k in range(N)):
            return j
    return None

visited=set(); orbits=[]
for i,c in enumerate(cubes_flat):
    if i in visited: continue
    orb=[]; cur=c.copy()
    for k in range(4):
        j=find_exact_cube(cur)
        if j is not None and j not in orb:
            orb.append(j)
        cur = matmul_mod(G_coeff, cur.reshape(N,1), P).reshape(N)
    for j in orb: visited.add(j)
    orbits.append(orb)
orbits=sorted(orbits, key=lambda x:(len(x), x))

# qz2/qw2 matrices from residual_y. q vars positions 3,4; z positions 5,6; w positions 7,8.
def extract_block_matrix(kind):
    M=np.zeros((2,3), dtype=object)
    if kind == "qz2":
        pairs=[(5,5),(5,6),(6,6)]
    elif kind == "qw2":
        pairs=[(7,7),(7,8),(8,8)]
    else:
        raise ValueError(kind)
    for qi,qvar in enumerate([3,4]):
        for ci,(a,b) in enumerate(pairs):
            M[qi,ci] = residual_y[MONO_IDX[tuple(sorted((qvar,a,b)))]] % P
    return M

qz2 = extract_block_matrix("qz2")
qw2 = extract_block_matrix("qw2")

# Conic intersection in the rowspace of a 2x3 matrix. Work projectively over F_p.
def conic_points_in_rowspace(M):
    r0=[int(M[0,j])%P for j in range(3)]
    r1=[int(M[1,j])%P for j in range(3)]
    points=[]
    # projective beta=1 affine chart: v=t*r0+r1. Also beta=0 point r0.
    def F(v):
        return (int(v[1])*int(v[1]) - 4*int(v[0])*int(v[2])) % P
    for t in range(P):
        v=[(t*r0[j]+r1[j])%P for j in range(3)]
        if v != [0,0,0] and F(v)==0:
            # normalize projectively by first nonzero entry
            for x in v:
                if x%P:
                    inv=pow(x,-1,P); break
            vn=tuple((x*inv)%P for x in v)
            if vn not in points: points.append(vn)
            if len(points) > 4:
                break
    v=r0
    if v != [0,0,0] and F(v)==0:
        for x in v:
            if x%P:
                inv=pow(x,-1,P); break
        vn=tuple((x*inv)%P for x in v)
        if vn not in points: points.append(vn)
    return points

qz_points=conic_points_in_rowspace(qz2)
qw_points=conic_points_in_rowspace(qw2)

# Known size-4 orbit reps and their z/w square lines in y-coordinates.
def square_line(pair):
    a=int(pair[0])%P; b=int(pair[1])%P
    return [(a*a)%P, (2*a*b)%P, (b*b)%P]

size4_orbit_records=[]
for orb in orbits:
    if len(orb)==4:
        rep=orb[0]
        ly=forms_y[rep]
        zsq=square_line([ly[5], ly[6]])
        wsq=square_line([ly[7], ly[8]])
        z_matches=[]
        w_matches=[]
        for pi,pt in enumerate(qz_points):
            ok,lam=scalar_projective_match(pt,zsq,P)
            if ok: z_matches.append({"point_index":pi,"lambda_point_over_known":int(lam)})
        for pi,pt in enumerate(qw_points):
            ok,lam=scalar_projective_match(pt,wsq,P)
            if ok: w_matches.append({"point_index":pi,"lambda_point_over_known":int(lam)})
        size4_orbit_records.append({
            "orbit": [int(x) for x in orb],
            "rep": int(rep),
            "p": vec_to_list(ly[0:3]),
            "q": vec_to_list(ly[3:5]),
            "z": vec_to_list(ly[5:7]),
            "w": vec_to_list(ly[7:9]),
            "z_square_line": vec_to_list(zsq),
            "w_square_line": vec_to_list(wsq),
            "z_conic_matches": z_matches,
            "w_conic_matches": w_matches,
        })

positive_control_ok = (
    int(sum(1 for x in anchor_diff if int(x)%P)) == 0 and
    int(sum(1 for x in y_anchor_diff if int(x)%P)) == 0 and
    any(rec["residual_diff_nonzero"] == 0 and rec["cube_set_projectively_preserved_with_lambda3_1"] for rec in action_records) and
    noninv_nonzero == 0 and other_inv_nonzero == 0 and
    rank_mod(qz2,P) == 2 and rank_mod(qw2,P) == 2 and
    len(qz_points) == 2 and len(qw_points) == 2 and
    all(len(r["z_conic_matches"]) == 1 and len(r["w_conic_matches"]) == 1 for r in size4_orbit_records)
)

result={
    "prime": P,
    "purpose": "pairing-convention repair and BILR positive control for Z4 eigenblock pencil-conic instrument",
    "a0": mat3_to_list(a0),
    "anchor_old_target_minus_free_minus_cubes_nonzero": int(sum(1 for x in anchor_diff if int(x)%P)),
    "action_tests": action_records,
    "selected_action": "pairing_rho__X_to_a0T_X_a0minusT",
    "selected_action_variable_formula": "M -> a0^T M a0^{-T} for the packed Euclidean pairing tr(L^T M)",
    "selected_action_R_transpose_equals_coefficient_conjugation_L_to_a0_L_a0inv": bool(Rt_equals_G),
    "imag_unit_mod_p": int(imag),
    "eigen_dims": dims,
    "change_rank": int(change_rank),
    "eigen_relation_R_change_equals_change_D_nonzero": eig_resid_nz,
    "block_dims": block_dims,
    "block_nonzero_counts_in_BILR_residual": block_nonzero,
    "residual_noninvariant_nonzero": noninv_nonzero,
    "residual_other_invariant_nonzero": other_inv_nonzero,
    "projection_changes_residual_nonzero": proj_diff_nz,
    "anchor_y_target_minus_free_minus_cubes_nonzero": int(sum(1 for x in y_anchor_diff if int(x)%P)),
    "cube_orbits_under_coefficient_conjugation": [{"indices":[int(x) for x in orb], "size":int(len(orb))} for orb in orbits],
    "qz2_matrix": mat3_to_list(qz2),
    "qw2_matrix": mat3_to_list(qw2),
    "qz2_rank": int(rank_mod(qz2,P)),
    "qw2_rank": int(rank_mod(qw2,P)),
    "qz2_conic_points_normalized": [list(map(int,pt)) for pt in qz_points],
    "qw2_conic_points_normalized": [list(map(int,pt)) for pt in qw_points],
    "size4_orbit_positive_control": size4_orbit_records,
    "positive_control_ok": bool(positive_control_ok),
    "interpretation": (
        "The residual is coefficientwise invariant for the transpose-pairing conjugation action, not for the raw Ad action tested in analysis. "
        "With the corrected action the residual occupies exactly the five invariant blocks and the qz2/qw2 conic intersections recover the two BILR size-4 cube orbits projectively. "
        "This validates the block instrument at the BILR rank-23 residual; it is not a rank-22 construction or exclusion by itself."
    ),
}

out=OUT/"pairing_pencil_positive_control.json"
out.write_text(json.dumps(result, indent=2)+"\n")
print(json.dumps({
    "anchor_old_nz": result["anchor_old_target_minus_free_minus_cubes_nonzero"],
    "action_tests": [{"name":r["name"],"residual_nz":r["residual_diff_nonzero"],"target_nz":r["target_diff_nonzero"],"cube_preserved":r["cube_set_projectively_preserved_with_lambda3_1"]} for r in action_records],
    "selected_Rt_equals_G": result["selected_action_R_transpose_equals_coefficient_conjugation_L_to_a0_L_a0inv"],
    "eigen_dims": dims,
    "block_dims": block_dims,
    "noninv_nz": noninv_nonzero,
    "other_inv_nz": other_inv_nonzero,
    "anchor_y_nz": result["anchor_y_target_minus_free_minus_cubes_nonzero"],
    "orbits": result["cube_orbits_under_coefficient_conjugation"],
    "qz2_rank": result["qz2_rank"],
    "qw2_rank": result["qw2_rank"],
    "qz_points": result["qz2_conic_points_normalized"],
    "positive_control_ok": result["positive_control_ok"],
    "out": str(out),
}, indent=2))
