#!/usr/bin/env python3
"""
analysis: Z4-equivariant m=4 exterior fiber correction and rank-10 residual instruments.

This script checks the symmetry explanation of the analysis tangent
space: the 10-dimensional tangent kernel of
    (A,B,C) in sl3^3 -> S4(A wedge B wedge C)
is exactly generated by
    * 8 internal SL3 recombinations of the three columns (A,B,C), and
    * 2 nontrivial centralizer-conjugation directions for a0.

It also anchors the corrected residual formula at the BILR point and computes
small exact modular tangent data for Z4-stable 10-cube orbit patterns.  These
pattern data are not nonexistence proofs; they make the next algebraic systems
explicit and help separate concise from automatically non-concise patterns.
"""
from __future__ import annotations

import itertools
import json
import math
import sys
from pathlib import Path

import numpy as np
import sympy as sp

WS = Path(__file__).resolve().parent.parent
OUT = WS / "data" / "z4_symmetry_kernel"
OUT.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(WS / "scripts"))
import ballard_z4_cyclic_scheme as bilr  # noqa: E402

n = 3
N = 9
P_MAIN = 65521
P_CHECK = 32003
TRIPLES = list(itertools.combinations(range(N), 3))
D = len(TRIPLES)
MONOS = list(itertools.combinations_with_replacement(range(N), 3))
PERMS = {m: sorted(set(itertools.permutations(m))) for m in MONOS}


def det3(m: np.ndarray) -> int:
    return int(
        m[0, 0] * (m[1, 1] * m[2, 2] - m[1, 2] * m[2, 1])
        - m[0, 1] * (m[1, 0] * m[2, 2] - m[1, 2] * m[2, 0])
        + m[0, 2] * (m[1, 0] * m[2, 1] - m[1, 1] * m[2, 0])
    )


def wedge3(u: np.ndarray, v: np.ndarray, w: np.ndarray) -> np.ndarray:
    r = np.zeros(D, dtype=object)
    for idx, (a, b, c) in enumerate(TRIPLES):
        mat = np.array(
            [[u[a], v[a], w[a]], [u[b], v[b], w[b]], [u[c], v[c], w[c]]],
            dtype=object,
        )
        r[idx] = det3(mat)
    return r


def rank_mod(A, p: int) -> int:
    A = np.array(A, dtype=object)
    m, ncols = A.shape
    B = [[int(A[i, j]) % p for j in range(ncols)] for i in range(m)]
    r = 0
    for c in range(ncols):
        piv = None
        for i in range(r, m):
            if B[i][c] % p:
                piv = i
                break
        if piv is None:
            continue
        B[r], B[piv] = B[piv], B[r]
        inv = pow(B[r][c] % p, -1, p)
        B[r] = [(x * inv) % p for x in B[r]]
        for i in range(m):
            if i != r and B[i][c] % p:
                f = B[i][c] % p
                B[i] = [(B[i][j] - f * B[r][j]) % p for j in range(ncols)]
        r += 1
        if r == m:
            break
    return r


def kernel_mod(A, p: int) -> tuple[np.ndarray, int]:
    A = np.array(A, dtype=object)
    m, ncols = A.shape
    B = [[int(A[i, j]) % p for j in range(ncols)] for i in range(m)]
    pivots = []
    r = 0
    for c in range(ncols):
        piv = None
        for i in range(r, m):
            if B[i][c] % p:
                piv = i
                break
        if piv is None:
            continue
        B[r], B[piv] = B[piv], B[r]
        inv = pow(B[r][c] % p, -1, p)
        B[r] = [(x * inv) % p for x in B[r]]
        for i in range(m):
            if i != r and B[i][c] % p:
                f = B[i][c] % p
                B[i] = [(B[i][j] - f * B[r][j]) % p for j in range(ncols)]
        pivots.append(c)
        r += 1
        if r == m:
            break
    free = [c for c in range(ncols) if c not in pivots]
    K = np.zeros((ncols, len(free)), dtype=object)
    for k, fc in enumerate(free):
        K[fc, k] = 1
        for i, pc in enumerate(pivots):
            K[pc, k] = (-B[i][fc]) % p
    return K, len(pivots)


def rank_Q(A) -> int:
    return int(sp.Matrix([[int(x) for x in row] for row in np.array(A, dtype=object).tolist()]).rank())


def nullspace_int(A) -> np.ndarray:
    ns = sp.Matrix([[int(x) for x in row] for row in np.array(A, dtype=object).tolist()]).nullspace()
    if not ns:
        return np.zeros((np.array(A).shape[1], 0), dtype=object)
    cols = []
    for v in ns:
        den = 1
        for entry in v:
            den = sp.ilcm(den, int(sp.denom(entry)))
        arr = [int(entry * den) for entry in v]
        # primitive normalization
        g = 0
        for a in arr:
            g = math.gcd(g, abs(a))
        if g > 1:
            arr = [a // g for a in arr]
        cols.append(arr)
    return np.array(cols, dtype=object).T


def sl3_basis_vecs() -> np.ndarray:
    B = []
    for i in range(3):
        for j in range(3):
            if i != j:
                v = np.zeros(9, dtype=object)
                v[3 * i + j] = 1
                B.append(v)
    h1 = np.zeros(9, dtype=object)
    h1[0] = 1
    h1[4] = -1
    B.append(h1)
    h2 = np.zeros(9, dtype=object)
    h2[4] = 1
    h2[8] = -1
    B.append(h2)
    return np.array(B, dtype=object).T  # 9 x 8


def sl3_coords(v: np.ndarray) -> np.ndarray:
    v = np.array(v, dtype=object).reshape(9)
    out = np.zeros(8, dtype=object)
    off = 0
    for i in range(3):
        for j in range(3):
            if i != j:
                out[off] = v[3 * i + j]
                off += 1
    out[6] = v[0]
    out[7] = -v[8]
    # Verify diagonal reconstruction when trace is zero.
    rec = sl3_basis_vecs() @ out
    if any(int(rec[i] - v[i]) != 0 for i in range(9)):
        raise ValueError(f"vector is not in the chosen sl3 span: {v.tolist()} -> {rec.tolist()}")
    return out


def sl3_generators_3x3() -> list[np.ndarray]:
    G = []
    for i in range(3):
        for j in range(3):
            if i != j:
                M = np.zeros((3, 3), dtype=object)
                M[i, j] = 1
                G.append(M)
    H1 = np.diag([1, -1, 0]).astype(object)
    H2 = np.diag([0, 1, -1]).astype(object)
    G.extend([H1, H2])
    return G


def build_a0_ad_s4():
    a0 = np.array([[0, 0, -1], [1, 0, -1], [0, 1, -1]], dtype=object)
    I3 = np.eye(3, dtype=object)
    powers = [I3]
    for _ in range(3):
        powers.append(powers[-1] @ a0)
    assert np.array_equal(powers[3] @ a0, I3)
    a0inv = powers[3]

    Ad = np.zeros((N, N), dtype=object)
    for i in range(3):
        for j in range(3):
            for k in range(3):
                for l in range(3):
                    Ad[3 * i + j, 3 * k + l] = a0[i, k] * a0inv[l, j]
    Ad_pows = [np.eye(N, dtype=object)]
    for _ in range(3):
        Ad_pows.append(Ad_pows[-1] @ Ad)

    L3 = np.zeros((D, D), dtype=object)
    for j, (a, b, c) in enumerate(TRIPLES):
        L3[:, j] = wedge3(Ad[:, a], Ad[:, b], Ad[:, c])
    L3_pows = [np.eye(D, dtype=object)]
    for _ in range(3):
        L3_pows.append(L3_pows[-1] @ L3)
    S4 = sum(L3_pows)
    return a0, powers, Ad, Ad_pows, S4


def omega_gl3() -> np.ndarray:
    omega = np.zeros(D, dtype=object)
    for idx, (pi, qi, ri) in enumerate(TRIPLES):
        a, b = pi // 3, pi % 3
        c, d = qi // 3, qi % 3
        e, f = ri // 3, ri % 3
        omega[idx] = (1 if d == e and b == c and a == f else 0) - (1 if f == c and b == e and a == d else 0)
    return omega


def exterior_jacobian_sl3(S4, U0, V0, W0, Bsl) -> np.ndarray:
    J = np.zeros((D, 24), dtype=object)
    for k in range(8):
        e = Bsl[:, k]
        J[:, k] = S4 @ wedge3(e, V0, W0)
        J[:, 8 + k] = S4 @ wedge3(U0, e, W0)
        J[:, 16 + k] = S4 @ wedge3(U0, V0, e)
    return J


def internal_direction_columns(U0, V0, W0) -> tuple[np.ndarray, list[dict]]:
    T = np.stack([U0, V0, W0], axis=1)  # 9 x 3 columns
    cols = []
    meta = []
    for gi, G in enumerate(sl3_generators_3x3()):
        dT = T @ G
        c = np.concatenate([sl3_coords(dT[:, 0]), sl3_coords(dT[:, 1]), sl3_coords(dT[:, 2])])
        cols.append(c)
        meta.append({"kind": "internal_SL3", "generator": gi, "matrix": [[int(x) for x in row] for row in G.tolist()]})
    return np.array(cols, dtype=object).T, meta


def centralizer_direction_columns(a0, U0, V0, W0) -> tuple[np.ndarray, list[dict]]:
    A = U0.reshape(3, 3)
    B = V0.reshape(3, 3)
    C = W0.reshape(3, 3)
    Xs = [a0, a0 @ a0]  # I gives zero commutator; these span the nontrivial PGL centralizer directions.
    cols = []
    meta = []
    for xi, X in enumerate(Xs):
        dA = (X @ A - A @ X).reshape(9)
        dB = (X @ B - B @ X).reshape(9)
        dC = (X @ C - C @ X).reshape(9)
        cols.append(np.concatenate([sl3_coords(dA), sl3_coords(dB), sl3_coords(dC)]))
        meta.append({"kind": "centralizer_conjugation", "generator": "a0" if xi == 0 else "a0^2"})
    return np.array(cols, dtype=object).T, meta


def prod_coeff_vec(u, v, w) -> np.ndarray:
    u = [int(x) for x in np.array(u, dtype=object).reshape(9)]
    v = [int(x) for x in np.array(v, dtype=object).reshape(9)]
    w = [int(x) for x in np.array(w, dtype=object).reshape(9)]
    out = np.zeros(len(MONOS), dtype=object)
    for mi, mono in enumerate(MONOS):
        s = 0
        for perm in PERMS[mono]:
            s += u[perm[0]] * v[perm[1]] * w[perm[2]]
        out[mi] = s
    return out


def cube_coeff_vec(l) -> np.ndarray:
    return prod_coeff_vec(l, l, l)


def cube_deriv_vec(l, dl) -> np.ndarray:
    return prod_coeff_vec(dl, l, l) + prod_coeff_vec(l, dl, l) + prod_coeff_vec(l, l, dl)


def orbit_cube_coeff(l, Ad_pows, orbit_len: int) -> np.ndarray:
    s = np.zeros(len(MONOS), dtype=object)
    for k in range(orbit_len):
        lk = Ad_pows[k] @ l
        s += cube_coeff_vec(lk)
    return s


def orbit_cube_deriv(l, dl, Ad_pows, orbit_len: int) -> np.ndarray:
    s = np.zeros(len(MONOS), dtype=object)
    for k in range(orbit_len):
        lk = Ad_pows[k] @ l
        dlk = Ad_pows[k] @ dl
        s += cube_deriv_vec(lk, dlk)
    return s


def free_orbit_diag_coeff_from_cols(Tcols, Ad_pows) -> np.ndarray:
    # diagonal polynomial contribution of four cyclic free orbits is
    # 3 * sum_k l_{A_k} l_{B_k} l_{C_k}.
    A, B, C = Tcols[:, 0], Tcols[:, 1], Tcols[:, 2]
    s = np.zeros(len(MONOS), dtype=object)
    for k in range(4):
        s += 3 * prod_coeff_vec(Ad_pows[k] @ A, Ad_pows[k] @ B, Ad_pows[k] @ C)
    return s


def residual_internal_derivative(Tcols, dTcols, Ad_pows) -> np.ndarray:
    A, B, C = Tcols[:, 0], Tcols[:, 1], Tcols[:, 2]
    dA, dB, dC = dTcols[:, 0], dTcols[:, 1], dTcols[:, 2]
    s = np.zeros(len(MONOS), dtype=object)
    for k in range(4):
        Ak, Bk, Ck = Ad_pows[k] @ A, Ad_pows[k] @ B, Ad_pows[k] @ C
        dAk, dBk, dCk = Ad_pows[k] @ dA, Ad_pows[k] @ dB, Ad_pows[k] @ dC
        s += -3 * (prod_coeff_vec(dAk, Bk, Ck) + prod_coeff_vec(Ak, dBk, Ck) + prod_coeff_vec(Ak, Bk, dCk))
    return s


def target_trM3_vec() -> np.ndarray:
    out = np.zeros(len(MONOS), dtype=object)
    idx = {m: i for i, m in enumerate(MONOS)}
    for a, b, c in itertools.product(range(3), repeat=3):
        mono = tuple(sorted([3 * a + b, 3 * b + c, 3 * c + a]))
        out[idx[mono]] += 1
    return out


def coeff_dict_to_vec(dct: dict) -> np.ndarray:
    idx = {m: i for i, m in enumerate(MONOS)}
    out = np.zeros(len(MONOS), dtype=object)
    for key, val in dct.items():
        out[idx[tuple(key)]] = val
    return out


def random_combo_basis(B: np.ndarray, rng: np.random.Generator, p: int) -> np.ndarray:
    coeff = rng.integers(0, p, size=B.shape[1], dtype=np.int64)
    v = np.zeros(B.shape[0], dtype=object)
    for i, c in enumerate(coeff):
        v += int(c) * B[:, i]
    return np.array([int(x) % p for x in v], dtype=object)


def orbit_span_dim(vectors: list[np.ndarray], p: int) -> int:
    if not vectors:
        return 0
    return rank_mod(np.stack(vectors, axis=1), p)


def pattern_tangent_data(Ad, Ad_pows, U0, V0, W0):
    # Build rational bases for the fixed spaces of Ad and Ad^2.
    I9 = np.eye(9, dtype=object)
    V1 = nullspace_int(Ad - I9)         # dim 3
    V2 = nullspace_int(Ad @ Ad - I9)    # dim 5 = V1 plus V_{-1}
    V4 = I9                             # ambient 9-space for nominal length 4 representatives
    spaces = {1: V1, 2: V2, 4: V4}
    lengths = {1: 1, 2: 2, 4: 4}

    rng = np.random.default_rng(42042)
    T0 = np.stack([U0, V0, W0], axis=1)
    # Use a simple determinant-one internal point, not necessarily a solution of a rank-10 system.
    Mcur = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]], dtype=object)
    Tcur = T0 @ Mcur

    residual_cols = []
    for G in sl3_generators_3x3():
        residual_cols.append(residual_internal_derivative(Tcur, Tcur @ G, Ad_pows))
    Jres = np.stack(residual_cols, axis=1)
    res_rank = rank_mod(Jres, P_MAIN)

    partitions = []
    def rec(rem, max_part, cur):
        if rem == 0:
            partitions.append(tuple(cur))
            return
        for part in [4, 2, 1]:
            if part <= rem and part <= max_part:
                rec(rem - part, part, cur + [part])
    rec(10, 4, [])

    highlighted = {(4,4,2), (4,4,1,1), (4,2,2,1,1), (4,2,2,2)}
    records = []
    for pat in partitions:
        cube_cols = []
        orbit_forms = []
        param_dims = []
        for part in pat:
            B = spaces[part]
            # choose a random representative in the correct fixed space
            l = random_combo_basis(B, rng, P_MAIN)
            # avoid zero; for tangent rank this is enough
            if not any(int(x) % P_MAIN for x in l):
                l = np.array(B[:, 0], dtype=object)
            param_dims.append(int(B.shape[1]))
            for k in range(lengths[part]):
                orbit_forms.append(np.array([int(x) % P_MAIN for x in (Ad_pows[k] @ l)], dtype=object))
            for bi in range(B.shape[1]):
                dl = B[:, bi]
                cube_cols.append(orbit_cube_deriv(l, dl, Ad_pows, lengths[part]))
        Jcube = np.stack(cube_cols, axis=1) if cube_cols else np.zeros((len(MONOS), 0), dtype=object)
        Jall = np.concatenate([Jres, -Jcube], axis=1)
        cube_tangent_rank = rank_mod(Jcube, P_MAIN)
        combined_rank = rank_mod(Jall, P_MAIN)
        form_span = orbit_span_dim(orbit_forms, P_MAIN)
        records.append({
            "pattern": list(pat),
            "number_of_cube_terms": int(sum(pat)),
            "parameter_dims_by_orbit": param_dims,
            "cube_parameter_dim": int(sum(param_dims)),
            "with_internal_SL3_parameter_dim": int(8 + sum(param_dims)),
            "random_orbit_linear_form_span_dim_mod_65521": int(form_span),
            "can_be_concise_by_span_test": bool(form_span == 9),
            "cube_tangent_rank_mod_65521": int(cube_tangent_rank),
            "combined_residual_minus_cube_tangent_rank_mod_65521": int(combined_rank),
            "highlighted_for_next_exact_system": bool(pat in highlighted),
        })
    return {
        "V1_fixed_dim": int(V1.shape[1]),
        "V2_Ad2_fixed_dim": int(V2.shape[1]),
        "residual_internal_tangent_rank_mod_65521": int(res_rank),
        "partitions_of_10_by_Z4_orbit_sizes_4_2_1": records,
        "interpretation": (
            "These are tangent and conciseness data for explicit Z4-stable 10-cube systems. "
            "They are not algebraic nonexistence results. Patterns whose sampled orbit forms span <9 cannot give a concise 9-variable residual on the open branch; "
            "the non-concise apolar branch still requires the polar-rank equations."
        ),
    }


def main():
    a0, powers, Ad, Ad_pows, S4 = build_a0_ad_s4()
    omega = omega_gl3()
    Bsl = sl3_basis_vecs()

    scheme = json.loads((WS / "data" / "ballard_z4_cyclic" / "ballard_z4_cyclic_scheme.json").read_text())
    U0 = np.array(scheme["free_orbit_representatives"][0]["U"], dtype=object).reshape(9)
    V0 = np.array(scheme["free_orbit_representatives"][0]["V"], dtype=object).reshape(9)
    W0 = np.array(scheme["free_orbit_representatives"][0]["W"], dtype=object).reshape(9)
    T0 = np.stack([U0, V0, W0], axis=1)

    # Exterior equation anchor.
    exterior0 = S4 @ wedge3(U0, V0, W0)
    exterior_matches = all(int(exterior0[i] - omega[i]) == 0 for i in range(D))

    # Jacobian and kernel.
    J = exterior_jacobian_sl3(S4, U0, V0, W0, Bsl)
    jr_Q = rank_Q(J)
    jr_p = rank_mod(J, P_MAIN)
    jr_p2 = rank_mod(J, P_CHECK)
    Kp, _ = kernel_mod(J, P_MAIN)

    internal_dirs, internal_meta = internal_direction_columns(U0, V0, W0)
    centralizer_dirs, centralizer_meta = centralizer_direction_columns(a0, U0, V0, W0)
    sym_dirs = np.concatenate([internal_dirs, centralizer_dirs], axis=1)
    sym_rank_Q = rank_Q(sym_dirs)
    sym_rank_p = rank_mod(sym_dirs, P_MAIN)
    Jsym = J @ sym_dirs
    Jsym_exact_nonzero = int(sum(1 for x in np.array(Jsym, dtype=object).reshape(-1) if int(x) != 0))
    Jsym_rank_p = rank_mod(Jsym, P_MAIN)
    combined_with_kernel_rank_p = rank_mod(np.concatenate([sym_dirs, Kp], axis=1), P_MAIN)

    # Linear truncation examples: internal tangent integrates as T0*(I+tN), but preserves exterior exactly only if det(I+tN)=1.
    I3 = np.eye(3, dtype=object)
    lin_examples = []
    for label, Nmat in [
        ("nilpotent_E01", sl3_generators_3x3()[0]),
        ("diagonal_H1", sl3_generators_3x3()[6]),
        ("diagonal_H1_plus_H2", sl3_generators_3x3()[6] + sl3_generators_3x3()[7]),
    ]:
        Mlin = I3 + Nmat
        Tlin = T0 @ Mlin
        ext = S4 @ wedge3(Tlin[:, 0], Tlin[:, 1], Tlin[:, 2])
        detM = int(round(sp.Matrix([[int(x) for x in row] for row in Mlin.tolist()]).det()))
        resid = [int(ext[i] - omega[i]) for i in range(D)]
        scale_resid = [int(ext[i] - detM * omega[i]) for i in range(D)]
        lin_examples.append({
            "label": label,
            "det_I_plus_N": detM,
            "equals_omega": bool(all(x == 0 for x in resid)),
            "equals_det_times_omega": bool(all(x == 0 for x in scale_resid)),
            "max_abs_ext_minus_omega": int(max(abs(x) for x in resid)),
        })

    # Centralizer finite conjugation is exact; first-order linear truncation need not be.
    A0 = U0.reshape(3, 3); B0 = V0.reshape(3, 3); C0 = W0.reshape(3, 3)
    X = a0
    dA = (X @ A0 - A0 @ X).reshape(9)
    dB = (X @ B0 - B0 @ X).reshape(9)
    dC = (X @ C0 - C0 @ X).reshape(9)
    ext_linear_cent = S4 @ wedge3(U0 + dA, V0 + dB, W0 + dC)
    lin_cent_resid = [int(ext_linear_cent[i] - omega[i]) for i in range(D)]
    Aconj = (a0 @ A0 @ powers[3]).reshape(9)
    Bconj = (a0 @ B0 @ powers[3]).reshape(9)
    Cconj = (a0 @ C0 @ powers[3]).reshape(9)
    ext_finite_cent = S4 @ wedge3(Aconj, Bconj, Cconj)
    finite_cent_resid = [int(ext_finite_cent[i] - omega[i]) for i in range(D)]

    # Residual anchor at BILR.
    tr_vec = target_trM3_vec()
    terms, cubes, free_orbits, powers_obj, _ = bilr.build_scheme()
    cube_vec = coeff_dict_to_vec(bilr.cube_coeffs(cubes))
    orbit_vec_from_single = free_orbit_diag_coeff_from_cols(T0, Ad_pows)
    residual_vec = tr_vec - orbit_vec_from_single
    residual_mismatch = [int(residual_vec[i] - cube_vec[i]) for i in range(len(MONOS))]
    residual_match = all(x == 0 for x in residual_mismatch)

    # Show a nontrivial internal SL3 move changes the residual but keeps exterior.
    Munip = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]], dtype=object)
    Tunip = T0 @ Munip
    ext_unip = S4 @ wedge3(Tunip[:, 0], Tunip[:, 1], Tunip[:, 2])
    ext_unip_ok = all(int(ext_unip[i] - omega[i]) == 0 for i in range(D))
    residual_unip = tr_vec - free_orbit_diag_coeff_from_cols(Tunip, Ad_pows)
    residual_unip_diff = [int(residual_unip[i] - cube_vec[i]) for i in range(len(MONOS))]

    bilr_analysis = json.loads((WS / "data" / "ballard_z4_cyclic" / "ballard_cyclic_analysis_v2.json").read_text())
    koszul_ranks = bilr_analysis.get("residual_cube_koszul_ranks_mod_primes", {})

    pat_data = pattern_tangent_data(Ad, Ad_pows, U0, V0, W0)

    result = {
        "field_setting": "characteristic zero checked by exact integer ranks and by good-prime modular ranks",
        "a0": [[int(x) for x in row] for row in a0.tolist()],
        "exterior_equation": "S4*(A wedge B wedge C) = omega for the BILR base triple",
        "bilr_base_exterior_matches_omega": bool(exterior_matches),
        "sl3_exterior_jacobian_shape": list(J.shape),
        "sl3_exterior_jacobian_rank_Q": int(jr_Q),
        "sl3_exterior_jacobian_rank_mod_65521": int(jr_p),
        "sl3_exterior_jacobian_rank_mod_32003": int(jr_p2),
        "kernel_dim": int(24 - jr_Q),
        "symmetry_directions": {
            "internal_SL3_recombination_columns": 8,
            "centralizer_conjugation_columns": 2,
            "rank_Q": int(sym_rank_Q),
            "rank_mod_65521": int(sym_rank_p),
            "rank_of_J_times_symmetry_dirs_mod_65521": int(Jsym_rank_p),
            "exact_nonzero_entries_of_J_times_symmetry_dirs": int(Jsym_exact_nonzero),
            "rank_of_symmetry_dirs_plus_modular_kernel_basis_mod_65521": int(combined_with_kernel_rank_p),
            "equals_full_tangent_kernel": bool(sym_rank_Q == 10 and Jsym_exact_nonzero == 0 and Jsym_rank_p == 0 and combined_with_kernel_rank_p == 10),
            "internal_meta": internal_meta,
            "centralizer_meta": centralizer_meta,
        },
        "linear_truncation_correction": {
            "internal_examples": lin_examples,
            "centralizer_linear_truncation_equals_omega": bool(all(x == 0 for x in lin_cent_resid)),
            "centralizer_linear_truncation_max_abs_error": int(max(abs(x) for x in lin_cent_resid)),
            "centralizer_finite_conjugation_equals_omega": bool(all(x == 0 for x in finite_cent_resid)),
            "message": "Tangent directions integrate through SL3 recombination or finite centralizer conjugation. A one-ARTIFACT affine tangent move preserves the exterior equation only in special cases such as det(I+N)=1 for pure internal moves; analysis's affine-linear reading is not used.",
        },
        "residual_anchor": {
            "formula": "C_M = tr(X^3) - 3*sum_{k=0}^3 (Ad^k A_M)(Ad^k B_M)(Ad^k C_M) in polynomial coefficients",
            "identity_internal_M_residual_equals_11_BILR_cubes": bool(residual_match),
            "identity_residual_mismatch_nonzero_count": int(sum(1 for x in residual_mismatch if x)),
            "BILR_residual_koszul_ranks_from": koszul_ranks,
            "rank_one_koszul_upper_per_cube": 70,
            "koszul_rank_722_rules_out_10_cubes_at_BILR_residual": bool(koszul_ranks and min(int(v) for v in koszul_ranks.values()) > 700),
            "unipotent_internal_move_det": 1,
            "unipotent_internal_move_preserves_exterior": bool(ext_unip_ok),
            "unipotent_residual_differs_from_BILR_cube_residual_nonzero_coefficients": int(sum(1 for x in residual_unip_diff if x)),
        },
        "rank10_Z4_orbit_pattern_tangent_data": pat_data,
    }

    out = OUT / "z4_symmetry_kernel_and_residual.json"
    out.write_text(json.dumps(result, indent=2) + "\n")

    print(json.dumps({
        "jacobian_rank_Q": result["sl3_exterior_jacobian_rank_Q"],
        "kernel_dim": result["kernel_dim"],
        "symmetry_rank_Q": result["symmetry_directions"]["rank_Q"],
        "J_sym_rank_mod_65521": result["symmetry_directions"]["rank_of_J_times_symmetry_dirs_mod_65521"],
        "symmetry_equals_kernel": result["symmetry_directions"]["equals_full_tangent_kernel"],
        "residual_anchor_matches_11_cubes": result["residual_anchor"]["identity_internal_M_residual_equals_11_BILR_cubes"],
        "unipotent_changes_residual_coeffs": result["residual_anchor"]["unipotent_residual_differs_from_BILR_cube_residual_nonzero_coefficients"],
        "highlighted_patterns": [r for r in pat_data["partitions_of_10_by_Z4_orbit_sizes_4_2_1"] if r["highlighted_for_next_exact_system"]],
        "out": str(out),
    }, indent=2))


if __name__ == "__main__":
    main()
