#!/usr/bin/env python3
"""Untrusted data producer; Lean checks every action and orbit certificate."""

from collections import deque
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPS = [(19, 10), (20, 10), (68, 10), (84, 10), (96, 10), (258, 10), (275, 10), (163, 84)]
SIZES = [98, 2352, 1176, 3528, 14112, 4704, 4704, 1344]
EXTRA_REPS = [(2, 1), (10, 1), (16, 1), (20, 1), (84, 1), (160, 1)]
EXTRA_SIZES = [98, 441, 882, 3528, 1764, 4704]


def transform(g, a):
    if g == 0:
        return ((a >> 3) & 7) | ((a & 7) << 3) | (a & 448)
    if g == 1:
        return (a & 7) | (((a >> 6) & 7) << 3) | (((a >> 3) & 7) << 6)
    if g == 2:
        return a ^ ((a >> 3) & 7)
    return sum(((a >> (3 * j + i)) & 1) << (3 * i + j) for i in range(3) for j in range(3))


def pair(a, b):
    return tuple(sorted((a, b, a ^ b))[:2])


def words():
    found = {273: []}
    todo = deque(found)
    while todo:
        a = todo.popleft()
        for g in range(3):
            b = transform(g, a)
            if b not in found:
                found[b] = [g] + found[a]
                todo.append(b)
    assert len(found) == 168
    rows = ["[" + ", ".join(map(str, found.get(i, []))) + "]" for i in range(512)]
    source = """import QiushiPlaneOrbitGenerators

/-! Generated by tools/generate_finite_orbits.py. No producer output is trusted. -/
namespace QiushiMatmul.PlaneOrbit
set_option maxRecDepth 20000
set_option maxHeartbeats 16000000

def glWords : Vector (List (Fin 3)) 512 := \u27e8#[
""" + ",\n".join("  " + row for row in rows) + """
], by decide\u27e9

theorem glWords_complete : \u2200 c : Fin 512, (codeMat c.val).det \u2260 0 \u2192
    rowWord glWords[c] = codeMat c.val := by decide +kernel +revert

theorem invertible_word (M : Mat3) (h : IsUnit M.det) :
    \u2203 w : List (Fin 3), rowWord w = M := by
  refine \u27e8glWords[matrixCode M], ?_\u27e9
  have hc : codeMat (matrixCode M).val = M := codeMat_matrixCode M
  rw [glWords_complete (matrixCode M) (by rw [hc]; exact isUnit_iff_ne_zero.mp h), hc]

end QiushiMatmul.PlaneOrbit
"""
    (ROOT / "QiushiPlaneOrbitGL.lean").write_text(source)


def orbit(rep):
    root = pair(*rep)
    found = {root: (0, root)}
    todo = deque(found)
    while todo:
        a = todo.popleft()
        for g in range(4):
            b = pair(*(transform(g, x) for x in a))
            if b not in found:
                found[b] = (found[a][0] + 1, a)
                todo.append(b)
    entries = sorted(found)
    index = {p: i for i, p in enumerate(entries)}
    rows = []
    for a in entries:
        depth, parent = found[a]
        nxt = [index[pair(*(transform(g, x) for x in a))] for g in range(4)]
        rows.append((a, depth, index[parent], nxt))
    return index[root], rows


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("--orbit", type=int, choices=range(478, 492), action="append")
    parser.add_argument("--remaining-six", action="store_true")
    parser.add_argument("--block-size", type=int, default=128)
    args = parser.parse_args()
    if args.block_size <= 0:
        parser.error("block size must be positive")
    if args.remaining_six:
        records = enumerate(zip(EXTRA_REPS, EXTRA_SIZES), 478)
    else:
        words()
        records = enumerate(zip(REPS, SIZES), 484)
    for index, (rep, expected) in records:
        if args.orbit and index not in args.orbit:
            continue
        root, rows = orbit(rep)
        assert len(rows) == expected
        assert root == 0
        print(index, len(rows), "root", root, "depth", max(r[1] for r in rows))
        name = f"QiushiPlaneOrbit{index}"
        namespace = f"QiushiMatmul.PlaneOrbit.Orbit{index}"
        literals = []
        for (a, b), depth, parent, nxt in rows:
            literals.append("  \u27e8" + ", ".join(map(str, [a, b, depth, parent] + nxt)) + "\u27e9")
        data = f"""import QiushiPlaneOrbitCertificate

/-! Untrusted BFS data; all properties are proved in the checked shards. -/
namespace {namespace}
set_option maxRecDepth 20000
set_option maxHeartbeats 16000000

"""
        lookup_chunk = 128
        chunk_count = (expected + lookup_chunk - 1) // lookup_chunk
        for k in range(chunk_count):
            data += f"def rows{k} : Array OrbitRow := #[\n"
            data += ",\n".join(literals[k * lookup_chunk:(k + 1) * lookup_chunk]) + "]\n\n"
        data += "def blocks : Array (Array OrbitRow) := #[" + ", ".join(
            f"rows{k}" for k in range(chunk_count)) + "]\n\n"
        data += f"""def data : OrbitData {expected - 1} :=
  \u27e8fun i => (blocks.getD (i.val / {lookup_chunk}) #[]).getD (i.val % {lookup_chunk})
    \u27e80, 0, 0, 0, 0, 0, 0, 0\u27e9\u27e9

end {namespace}
"""
        (ROOT / (name + "Data.lean")).write_text(data)
        chunks = (expected + args.block_size - 1) // args.block_size
        shard_names = []
        for k in range(chunks):
            shard = name + f"Check{k}"
            shard_names.append(shard)
            source = f"""import {name}Data

namespace {namespace}
set_option maxRecDepth 20000
set_option maxHeartbeats 16000000

theorem checked{k} : \u2200 j : Fin {args.block_size},
    data.RowOK (data.ix ({k * args.block_size} + j.val)) := by decide +kernel +revert

end {namespace}
"""
            (ROOT / (shard + ".lean")).write_text(source)
        aggregate = "\n".join("import " + s for s in shard_names) + f"""

namespace {namespace}

theorem checked : \u2200 i, data.RowOK i := by
  apply OrbitData.of_blocks (k := {args.block_size})
  intro b
  fin_cases b
""" + "".join(f"  \u00b7 exact checked{k}\n" for k in range(chunks)) + f"""

theorem size : Nat.card {{W : Space // Equivalent (data.space 0) W}} = {expected} :=
  data.orbit_card checked

end {namespace}
"""
        (ROOT / (name + ".lean")).write_text(aggregate)


if __name__ == "__main__":
    main()
