-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiWcOrbit47Dispatch

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o116W_mono : Submodule F2 Mat3 := spanCodes [304, 160, 8, 2, 1]

private theorem o116W_mono_containment :
    o116W_mono ≤ o47W_wc := by
  unfold o116W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [304, 160, 68, 8, 2, 1] 304 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [304, 160, 68, 8, 2, 1] 160 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [304, 160, 68, 8, 2, 1] 8 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [304, 160, 68, 8, 2, 1] 2 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [304, 160, 68, 8, 2, 1] 1 (by decide))

theorem orbit116_lb14_mono : QuotientRankAtLeast o116W_mono 14 :=
  quotientRankAtLeast_mono o116W_mono_containment step109_orbit47_lb14_wc

end QiushiMatmul
