import QiushiMatmulFinitePremises
import QiushiOrbitTransport

/-!
# Exhaustive nonzero-line orbit reduction over `Mat_3(F_2)`

The three literal vectors below are generated by `gen_line_orbit.py`.  For
each of the 511 nonzero row-major matrix codes, they give two invertible
matrices and one of the rank-1/rank-2/rank-3 representatives 1, 17, 273.
All table properties used by the public theorem are rechecked by the Lean
kernel with `decide`.
-/

open Matrix BigOperators

attribute [local instance] Classical.propDecidable

noncomputable section

namespace QiushiMatmul

set_option maxRecDepth 100000

set_option maxHeartbeats 12000000 in
private theorem matrixCodeNat_lt_all : ∀ M : Mat3,
    (if M 0 0 = 1 then 1 else 0) +
    (if M 0 1 = 1 then 2 else 0) +
    (if M 0 2 = 1 then 4 else 0) +
    (if M 1 0 = 1 then 8 else 0) +
    (if M 1 1 = 1 then 16 else 0) +
    (if M 1 2 = 1 then 32 else 0) +
    (if M 2 0 = 1 then 64 else 0) +
    (if M 2 1 = 1 then 128 else 0) +
    (if M 2 2 = 1 then 256 else 0) < 512 := by decide

/-- The row-major code inverse to `codeMat`. -/
def matrixCodeNat (M : Mat3) : Nat :=
    (if M 0 0 = 1 then 1 else 0) +
    (if M 0 1 = 1 then 2 else 0) +
    (if M 0 2 = 1 then 4 else 0) +
    (if M 1 0 = 1 then 8 else 0) +
    (if M 1 1 = 1 then 16 else 0) +
    (if M 1 2 = 1 then 32 else 0) +
    (if M 2 0 = 1 then 64 else 0) +
    (if M 2 1 = 1 then 128 else 0) +
    (if M 2 2 = 1 then 256 else 0)

/-- A matrix code bundled with its `0 ≤ code < 512` range proof. -/
def matrixCode (M : Mat3) : Fin 512 :=
  ⟨matrixCodeNat M, matrixCodeNat_lt_all M⟩

set_option maxHeartbeats 12000000 in
private theorem codeMat_matrixCode_all : ∀ M : Mat3,
    codeMat (matrixCodeNat M) = M := by decide

lemma codeMat_matrixCode (M : Mat3) : codeMat (matrixCodeNat M) = M :=
  codeMat_matrixCode_all M

private def lineOrbitPCodeTable : Vector Nat 512 := ⟨#[
    273, 161, 161, 161, 161, 161, 161, 161, 98, 99, 266, 266, 266, 266, 266, 266,
    98, 266, 99, 266, 266, 266, 266, 266, 98, 266, 266, 99, 266, 266, 266, 266,
    98, 266, 266, 266, 99, 266, 266, 266, 98, 266, 266, 266, 266, 99, 266, 266,
    98, 266, 266, 266, 266, 266, 99, 266, 98, 266, 266, 266, 266, 266, 266, 99,
    84, 85, 140, 140, 140, 140, 140, 140, 86, 87, 142, 142, 142, 142, 142, 142,
    84, 85, 92, 93, 84, 84, 84, 84, 84, 85, 93, 92, 84, 84, 84, 84,
    84, 85, 84, 84, 92, 93, 84, 84, 84, 85, 84, 84, 93, 92, 84, 84,
    84, 85, 84, 84, 84, 84, 92, 93, 84, 85, 84, 84, 84, 84, 93, 92,
    84, 140, 85, 140, 140, 140, 140, 140, 84, 92, 85, 93, 84, 84, 84, 84,
    86, 142, 87, 142, 142, 142, 142, 142, 84, 93, 85, 92, 84, 84, 84, 84,
    84, 84, 85, 84, 92, 84, 93, 84, 84, 84, 85, 84, 84, 92, 84, 93,
    84, 84, 85, 84, 93, 84, 92, 84, 84, 84, 85, 84, 84, 93, 84, 92,
    84, 140, 140, 85, 140, 140, 140, 140, 84, 92, 93, 85, 84, 84, 84, 84,
    84, 93, 92, 85, 84, 84, 84, 84, 86, 142, 142, 87, 142, 142, 142, 142,
    84, 84, 84, 85, 92, 84, 84, 93, 84, 84, 84, 85, 84, 92, 93, 84,
    84, 84, 84, 85, 84, 93, 92, 84, 84, 84, 84, 85, 93, 84, 84, 92,
    84, 140, 140, 140, 85, 140, 140, 140, 84, 92, 84, 84, 85, 93, 84, 84,
    84, 84, 92, 84, 85, 84, 93, 84, 84, 84, 84, 92, 85, 84, 84, 93,
    86, 142, 142, 142, 87, 142, 142, 142, 84, 93, 84, 84, 85, 92, 84, 84,
    84, 84, 93, 84, 85, 84, 92, 84, 84, 84, 84, 93, 85, 84, 84, 92,
    84, 140, 140, 140, 140, 85, 140, 140, 84, 92, 84, 84, 93, 85, 84, 84,
    84, 84, 92, 84, 84, 85, 84, 93, 84, 84, 84, 92, 84, 85, 93, 84,
    84, 93, 84, 84, 92, 85, 84, 84, 86, 142, 142, 142, 142, 87, 142, 142,
    84, 84, 84, 93, 84, 85, 92, 84, 84, 84, 93, 84, 84, 85, 84, 92,
    84, 140, 140, 140, 140, 140, 85, 140, 84, 92, 84, 84, 84, 84, 85, 93,
    84, 84, 92, 84, 93, 84, 85, 84, 84, 84, 84, 92, 84, 93, 85, 84,
    84, 84, 93, 84, 92, 84, 85, 84, 84, 84, 84, 93, 84, 92, 85, 84,
    86, 142, 142, 142, 142, 142, 87, 142, 84, 93, 84, 84, 84, 84, 85, 92,
    84, 140, 140, 140, 140, 140, 140, 85, 84, 92, 84, 84, 84, 84, 93, 85,
    84, 84, 92, 84, 84, 93, 84, 85, 84, 84, 84, 92, 93, 84, 84, 85,
    84, 84, 84, 93, 92, 84, 84, 85, 84, 84, 93, 84, 84, 92, 84, 85,
    84, 93, 84, 84, 84, 84, 92, 85, 86, 142, 142, 142, 142, 142, 142, 87
  ], by decide⟩

private def lineOrbitQCodeTable : Vector Nat 512 := ⟨#[
    273, 161, 98, 225, 84, 169, 114, 233, 161, 161, 273, 275, 161, 165, 401, 403,
    98, 266, 98, 267, 98, 330, 102, 331, 225, 282, 281, 225, 225, 474, 473, 229,
    84, 140, 84, 204, 84, 141, 86, 205, 169, 172, 337, 467, 169, 169, 465, 339,
    114, 394, 116, 459, 114, 458, 114, 395, 233, 410, 345, 236, 233, 346, 409, 233,
    161, 161, 273, 275, 161, 165, 401, 403, 161, 161, 273, 275, 161, 165, 401, 403,
    273, 273, 273, 273, 273, 277, 305, 309, 275, 275, 275, 275, 275, 279, 311, 307,
    161, 161, 161, 163, 161, 161, 177, 179, 165, 165, 165, 167, 165, 165, 183, 181,
    401, 401, 417, 423, 401, 407, 401, 401, 403, 403, 421, 419, 403, 405, 403, 403,
    98, 266, 98, 267, 98, 330, 102, 331, 266, 266, 266, 266, 266, 298, 270, 302,
    98, 266, 98, 267, 98, 330, 102, 331, 267, 267, 267, 267, 267, 303, 271, 299,
    98, 98, 98, 99, 98, 106, 98, 107, 330, 354, 330, 359, 330, 330, 335, 330,
    102, 102, 102, 103, 102, 111, 102, 110, 331, 358, 331, 355, 331, 331, 334, 331,
    225, 282, 281, 225, 225, 474, 473, 229, 282, 282, 282, 282, 282, 314, 318, 286,
    281, 281, 281, 281, 281, 317, 313, 285, 225, 282, 281, 225, 225, 474, 473, 229,
    225, 226, 225, 225, 225, 250, 249, 225, 474, 482, 485, 474, 474, 474, 474, 477,
    473, 486, 481, 473, 473, 473, 473, 478, 229, 230, 229, 229, 229, 253, 254, 229,
    84, 140, 84, 204, 84, 141, 86, 205, 140, 140, 140, 156, 140, 140, 142, 158,
    84, 84, 84, 92, 84, 85, 84, 93, 204, 212, 204, 204, 204, 215, 207, 204,
    84, 140, 84, 204, 84, 141, 86, 205, 141, 141, 141, 159, 141, 141, 143, 157,
    86, 86, 86, 95, 86, 87, 86, 94, 205, 214, 205, 205, 205, 213, 206, 205,
    169, 172, 337, 467, 169, 169, 465, 339, 172, 172, 172, 188, 172, 172, 190, 174,
    337, 340, 337, 380, 337, 337, 377, 337, 467, 468, 492, 467, 467, 467, 467, 491,
    169, 169, 169, 187, 169, 169, 185, 171, 169, 172, 337, 467, 169, 169, 465, 339,
    465, 470, 489, 465, 465, 465, 465, 494, 339, 342, 339, 379, 339, 339, 382, 339,
    114, 394, 116, 459, 114, 458, 114, 395, 394, 394, 396, 444, 394, 442, 394, 394,
    116, 116, 116, 124, 116, 125, 116, 117, 459, 500, 460, 459, 459, 459, 459, 499,
    114, 114, 114, 123, 114, 122, 114, 115, 458, 498, 461, 458, 458, 458, 458, 501,
    114, 394, 116, 459, 114, 458, 114, 395, 395, 395, 397, 443, 395, 445, 395, 395,
    233, 410, 345, 236, 233, 346, 409, 233, 410, 410, 428, 412, 410, 426, 410, 410,
    345, 372, 345, 348, 345, 345, 369, 345, 236, 244, 236, 236, 236, 239, 247, 236,
    233, 242, 233, 233, 233, 234, 241, 233, 346, 370, 346, 351, 346, 346, 375, 346,
    409, 409, 425, 415, 409, 431, 409, 409, 233, 410, 345, 236, 233, 346, 409, 233
  ], by decide⟩

private def lineOrbitQTInvCodeTable : Vector Nat 512 := ⟨#[
    273, 161, 98, 163, 84, 165, 102, 167, 161, 161, 273, 281, 161, 169, 305, 313,
    98, 266, 98, 282, 98, 298, 114, 314, 163, 267, 275, 163, 163, 299, 307, 187,
    84, 140, 84, 156, 84, 172, 116, 188, 165, 141, 277, 285, 165, 165, 309, 317,
    102, 270, 86, 286, 102, 302, 102, 318, 167, 271, 279, 159, 167, 303, 311, 167,
    161, 161, 273, 281, 161, 169, 305, 313, 161, 161, 273, 281, 161, 169, 305, 313,
    273, 273, 273, 273, 273, 337, 401, 465, 281, 281, 281, 281, 281, 345, 409, 473,
    161, 161, 161, 225, 161, 161, 417, 481, 169, 169, 169, 233, 169, 169, 425, 489,
    305, 305, 177, 241, 305, 369, 305, 305, 313, 313, 185, 249, 313, 377, 313, 313,
    98, 266, 98, 282, 98, 298, 114, 314, 266, 266, 266, 266, 266, 330, 394, 458,
    98, 266, 98, 282, 98, 298, 114, 314, 282, 282, 282, 282, 282, 346, 410, 474,
    98, 98, 98, 226, 98, 354, 98, 482, 298, 106, 298, 234, 298, 298, 426, 298,
    114, 114, 114, 242, 114, 370, 114, 498, 314, 122, 314, 250, 314, 314, 442, 314,
    163, 267, 275, 163, 163, 299, 307, 187, 267, 267, 267, 267, 267, 331, 395, 459,
    275, 275, 275, 275, 275, 339, 403, 467, 163, 267, 275, 163, 163, 299, 307, 187,
    163, 99, 163, 163, 163, 355, 419, 163, 299, 107, 171, 299, 299, 299, 299, 491,
    307, 115, 179, 307, 307, 307, 307, 499, 187, 123, 187, 187, 187, 379, 443, 187,
    84, 140, 84, 156, 84, 172, 116, 188, 140, 140, 140, 204, 140, 140, 396, 460,
    84, 84, 84, 212, 84, 340, 84, 468, 156, 92, 156, 156, 156, 348, 412, 156,
    84, 140, 84, 156, 84, 172, 116, 188, 172, 172, 172, 236, 172, 172, 428, 492,
    116, 116, 116, 244, 116, 372, 116, 500, 188, 124, 188, 188, 188, 380, 444, 188,
    165, 141, 277, 285, 165, 165, 309, 317, 141, 141, 141, 205, 141, 141, 397, 461,
    277, 85, 277, 213, 277, 277, 405, 277, 285, 93, 157, 285, 285, 285, 285, 477,
    165, 165, 165, 229, 165, 165, 421, 485, 165, 141, 277, 285, 165, 165, 309, 317,
    309, 117, 181, 309, 309, 309, 309, 501, 317, 125, 317, 253, 317, 317, 445, 317,
    102, 270, 86, 286, 102, 302, 102, 318, 270, 270, 142, 206, 270, 334, 270, 270,
    86, 86, 86, 214, 86, 342, 86, 470, 286, 94, 158, 286, 286, 286, 286, 478,
    102, 102, 102, 230, 102, 358, 102, 486, 302, 110, 174, 302, 302, 302, 302, 494,
    102, 270, 86, 286, 102, 302, 102, 318, 318, 318, 190, 254, 318, 382, 318, 318,
    167, 271, 279, 159, 167, 303, 311, 167, 271, 271, 143, 207, 271, 335, 271, 271,
    279, 87, 279, 215, 279, 279, 407, 279, 159, 95, 159, 159, 159, 351, 415, 159,
    167, 103, 167, 167, 167, 359, 423, 167, 303, 111, 303, 239, 303, 303, 431, 303,
    311, 311, 183, 247, 311, 375, 311, 311, 167, 271, 279, 159, 167, 303, 311, 167
  ], by decide⟩

private def lineOrbitRankTable : Vector Nat 512 := ⟨#[
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
    0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
    0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
    0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
    0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
    1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
    0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
    0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1,
    0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
    1, 1, 1, 1, 2, 2, 2, 2, 0, 1, 1, 0, 1, 1, 1, 1,
    1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2,
    1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1,
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1,
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1,
    0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2,
    1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2,
    1, 1, 2, 2, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1,
    1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1,
    0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 1, 1,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2,
    1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2,
    0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 1, 1,
    0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1, 1,
    1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1,
    1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1,
    1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0
  ], by decide⟩

private def lineOrbitPCode (c : Fin 512) : Nat := lineOrbitPCodeTable[c]
private def lineOrbitQCode (c : Fin 512) : Nat := lineOrbitQCodeTable[c]
private def lineOrbitQTInvCode (c : Fin 512) : Nat := lineOrbitQTInvCodeTable[c]

set_option maxHeartbeats 12000000 in
private theorem lineOrbitRank_lt_all : ∀ c : Fin 512,
    lineOrbitRankTable[c] < 3 := by decide

def lineOrbitRank (c : Fin 512) : Fin 3 :=
  ⟨lineOrbitRankTable[c], lineOrbitRank_lt_all c⟩

def lineRepresentativeCode (k : Fin 3) : Nat :=
  match k.val with
  | 0 => 1
  | 1 => 17
  | _ => 273

def lineOrbitP (c : Fin 512) : Mat3 := codeMat (lineOrbitPCode c)
private def lineOrbitQ (c : Fin 512) : Mat3 := codeMat (lineOrbitQCode c)
def lineOrbitQTInv (c : Fin 512) : Mat3 := codeMat (lineOrbitQTInvCode c)

set_option maxHeartbeats 12000000 in
theorem lineOrbitP_det_ne_zero_all : ∀ c : Fin 512,
    (lineOrbitP c).det ≠ 0 := by decide

set_option maxHeartbeats 12000000 in
theorem lineOrbitQ_det_ne_zero_all : ∀ c : Fin 512,
    (lineOrbitQ c).det ≠ 0 := by decide

private lemma lineOrbitP_isUnitDet (c : Fin 512) : IsUnit (lineOrbitP c).det :=
  isUnit_iff_ne_zero.mpr (lineOrbitP_det_ne_zero_all c)

private lemma lineOrbitQ_isUnitDet (c : Fin 512) : IsUnit (lineOrbitQ c).det :=
  isUnit_iff_ne_zero.mpr (lineOrbitQ_det_ne_zero_all c)

set_option maxHeartbeats 12000000 in
theorem lineOrbitQTInv_right_inverse_all : ∀ c : Fin 512,
    (lineOrbitQ c).transpose * lineOrbitQTInv c = 1 := by decide

private lemma lineOrbitQTInv_eq (c : Fin 512) [Invertible (lineOrbitQ c)] :
    (lineOrbitQ c).transpose⁻¹ = lineOrbitQTInv c := by
  apply Matrix.inv_eq_right_inv
  exact lineOrbitQTInv_right_inverse_all c

set_option maxHeartbeats 12000000 in
theorem lineOrbit_action_explicit_all : ∀ c : Fin 512, c.val ≠ 0 →
    (lineOrbitP c).transpose *
      codeMat (lineRepresentativeCode (lineOrbitRank c)) * lineOrbitQTInv c =
        codeMat c.val := by decide

private lemma lineOrbit_action (c : Fin 512) [Invertible (lineOrbitQ c)]
    (hc : c.val ≠ 0) :
    actionA (lineOrbitP c) (lineOrbitQ c)
      (codeMat (lineRepresentativeCode (lineOrbitRank c))) = codeMat c.val := by
  rw [actionA, lineOrbitQTInv_eq]
  exact lineOrbit_action_explicit_all c hc

private lemma spanCodes_singleton (n : Nat) :
    spanCodes [n] = Submodule.span F2 {codeMat n} := by
  unfold spanCodes
  congr 1
  ext M
  simp

private lemma actionW_span_singleton (P Q M : Mat3) :
    actionW P Q (Submodule.span F2 {M}) =
      Submodule.span F2 {actionA P Q M} := by
  simp [actionW, Submodule.map_span, actionALinearMap]

private lemma representative_line_lb19 (P : FinitePremises) (k : Fin 3) :
    QuotientRankAtLeast
      (Submodule.span F2 {codeMat (lineRepresentativeCode k)}) 19 := by
  fin_cases k
  · simpa [lineRepresentativeCode, lineRank1, spanCodes_singleton] using P.line_rank1_lb19
  · simpa [lineRepresentativeCode, lineRank2, spanCodes_singleton] using P.line_rank2_lb19
  · simpa [lineRepresentativeCode, lineRank3, spanCodes_singleton] using P.line_rank3_lb19

/-- Every nonzero A-slot line is in the `GL_3(F_2) × GL_3(F_2)` orbit of
one of the three line representatives covered by `FinitePremises`. -/
theorem nonzero_line_lb19 (P : FinitePremises) (M : Mat3) (hM : M ≠ 0) :
    QuotientRankAtLeast (Submodule.span F2 {M}) 19 := by
  let c := matrixCode M
  have hcNat : matrixCodeNat M ≠ 0 := by
    intro hc
    apply hM
    exact (codeMat_matrixCode M).symm.trans (by rw [hc]; decide)
  have hc : c.val ≠ 0 := by simpa [c, matrixCode] using hcNat
  letI : Invertible (lineOrbitP c) :=
    Matrix.invertibleOfIsUnitDet _ (lineOrbitP_isUnitDet c)
  letI : Invertible (lineOrbitQ c) :=
    Matrix.invertibleOfIsUnitDet _ (lineOrbitQ_isUnitDet c)
  have hbase := representative_line_lb19 P (lineOrbitRank c)
  have htransport := quotientRankAtLeast_action
    (P := lineOrbitP c) (Q := lineOrbitQ c) hbase
  have hspan :
      actionW (lineOrbitP c) (lineOrbitQ c)
          (Submodule.span F2 {codeMat (lineRepresentativeCode (lineOrbitRank c))}) =
        Submodule.span F2 {M} := by
    rw [actionW_span_singleton, lineOrbit_action c hc]
    change Submodule.span F2 {codeMat (matrixCodeNat M)} = Submodule.span F2 {M}
    rw [codeMat_matrixCode]
  rwa [hspan] at htransport

end QiushiMatmul
end
