-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiWcOrbit75Dispatch

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o245W_mono : Submodule F2 Mat3 := spanCodes [262, 161, 68, 20, 10]

private theorem o245W_mono_containment :
    o245W_mono ≤ o75W_wc := by
  unfold o245W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 160, 68, 20, 10, 1] 262 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 160, 68, 20, 10, 1] 161 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 160, 68, 20, 10, 1] 68 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 160, 68, 20, 10, 1] 20 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 160, 68, 20, 10, 1] 10 (by decide))

theorem orbit245_lb16_mono : QuotientRankAtLeast o245W_mono 16 :=
  quotientRankAtLeast_mono o245W_mono_containment step109_orbit75_lb16_wc

end QiushiMatmul
