-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiWcOrbit96Dispatch

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o251W_mono : Submodule F2 Mat3 := spanCodes [20, 8, 2, 1]

private theorem o251W_mono_containment :
    o251W_mono ≤ o96W_wc := by
  unfold o251W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 20, 8, 2, 1] 20 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 20, 8, 2, 1] 8 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 20, 8, 2, 1] 2 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 20, 8, 2, 1] 1 (by decide))

theorem orbit251_lb16_mono : QuotientRankAtLeast o251W_mono 16 :=
  quotientRankAtLeast_mono o251W_mono_containment step109_orbit96_lb16_wc

end QiushiMatmul
