-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiWcOrbit220Dispatch

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o323W_mono : Submodule F2 Mat3 := spanCodes [192, 36, 16, 1]

private theorem o323W_mono_containment :
    o323W_mono ≤ o220W_wc := by
  unfold o323W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [334, 192, 36, 16, 1] 192 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [334, 192, 36, 16, 1] 36 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [334, 192, 36, 16, 1] 16 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [334, 192, 36, 16, 1] 1 (by decide))

theorem orbit323_lb15_mono : QuotientRankAtLeast o323W_mono 15 :=
  quotientRankAtLeast_mono o323W_mono_containment step109_orbit220_lb15_wc

end QiushiMatmul
