-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiWcOrbit85Dispatch

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o243W_mono : Submodule F2 Mat3 := spanCodes [131, 68, 35, 20, 10]

private theorem o243W_mono_containment :
    o243W_mono ≤ o85W_wc := by
  unfold o243W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 131, 68, 35, 20, 10] 131 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 131, 68, 35, 20, 10] 68 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 131, 68, 35, 20, 10] 35 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 131, 68, 35, 20, 10] 20 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [262, 131, 68, 35, 20, 10] 10 (by decide))

theorem orbit243_lb17_mono : QuotientRankAtLeast o243W_mono 17 :=
  quotientRankAtLeast_mono o243W_mono_containment step109_orbit85_lb17_wc

end QiushiMatmul
