-- Generated by step126_regen_transports.py
import QiushiCodeSpanCore
import QiushiMonotonicity
import QiushiMonoOrbit93From29

set_option maxHeartbeats 4000000
open BigOperators Finset Matrix
namespace QiushiMatmul

def o250W_mono : Submodule F2 Mat3 := spanCodes [16, 8, 2, 1]

private theorem o250W_mono_containment :
    o250W_mono ≤ o93W_mono := by
  unfold o250W_mono
  unfold spanCodes
  exact Submodule.span_le.mpr (by
    intro M hM
    rcases hM with ⟨n, hn, rfl⟩
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hn
    rcases hn with rfl | rfl | rfl | rfl
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 16, 8, 2, 1] 16 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 16, 8, 2, 1] 8 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 16, 8, 2, 1] 2 (by decide)
    · exact spanContainsCodeCore_implies_mem_spanCodes [68, 16, 8, 2, 1] 1 (by decide))

theorem orbit250_lb15_mono : QuotientRankAtLeast o250W_mono 15 :=
  quotientRankAtLeast_mono o250W_mono_containment orbit93_lb15_mono

end QiushiMatmul
