import QiushiStep128Orbit451Defs

set_option maxHeartbeats 400000000
set_option maxRecDepth 10000
set_option linter.unusedVariables false
open BigOperators Finset Matrix Classical
attribute [local instance] Classical.propDecidable
noncomputable section
namespace QiushiMatmul

theorem o451W_le_source (i : Fin 44) : o451W ≤ o451SourceU i := by
  intro M hM
  fin_cases i <;> simp only [o451SourceU]
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 273) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 154) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 64) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 58) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 4) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 271) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 68) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 30) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 267) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 64) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 30) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 267) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 68) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 36) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 30) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 271) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 68) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 36) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 30) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 267) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 90) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 58) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 4) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 363) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 224) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 4) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 395) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 68) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 36) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 331) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 335) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 299) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 68) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 299) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 164) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 64) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 271) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 96) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 303) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 96) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 273) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 4) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 267) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 32) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 4) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 132) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 100) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 164) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 96) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 273) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 64) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 267) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 128) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩, spanCodes_le_kerEvalFunc_of_gens' (codeMat 64) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 401) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 122) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 369) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 250) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 335) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 158) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 337) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 254) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 305) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 158) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 303) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 94) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 271) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 250) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 299) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 190) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 196) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 100) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 160) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 26) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact ⟨spanCodes_le_kerEvalFunc_of_gens' (codeMat 160) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM, spanCodes_le_kerEvalFunc_of_gens' (codeMat 100) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM⟩
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 369) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 405) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 501) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 491) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 335) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 431) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 122) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 250) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 158) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 94) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 190) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM
  · exact spanCodes_le_kerEvalFunc_of_gens' (codeMat 254) [257, 19, 10] (fun n hn => by fin_cases hn <;> decide) hM

end QiushiMatmul
end
