#!/usr/bin/env python3
"""Fast exact two-row capacity-cover scan for a live prefix frontier.

Uses 256-bit Python integers for row/future masks.  Assumes the frontier has
already passed the elementary cardinality and one-row cover tests if generated by
cover_exhaust_live_prefix; nevertheless it recomputes margins exactly.
"""
from __future__ import annotations
import argparse,json,struct,time,hashlib
from collections import Counter
from pathlib import Path
ROOT=Path('research/research_record')
COVER=ROOT/'workspace/data/domain_dfs_soundness/e11_wang_cap67_first512_cover.bin'
FRONT=ROOT/'workspace/data/domain_dfs_soundness/branch1_live_prefix_d10_cover512.jsonl'
OUT=ROOT/'workspace/data/domain_dfs_soundness/fast_pair_cover_stats.json'
MAGIC=b'E11WANG1'; REC='<BBHQQQQ'; RECSZ=struct.calcsize(REC)

def sha(p):
    h=hashlib.sha256();
    with Path(p).open('rb') as f:
        for c in iter(lambda:f.read(1<<20),b''): h.update(c)
    return h.hexdigest()

def load_cover(path,take):
    data=Path(path).read_bytes(); assert data[:8]==MAGIC
    n=struct.unpack_from('<I',data,8)[0]; off=12; rows=[]
    for i in range(n):
        cap,dim,res,w0,w1,w2,w3=struct.unpack_from(REC,data,off); off+=RECSZ
        if take and i>=take: continue
        mask=int(w0)|(int(w1)<<64)|(int(w2)<<128)|(int(w3)<<192)
        rows.append((int(cap),mask,i))
    return rows

def exact_pair_bound(avail,mi,mj,ui,uj):
    both=(mi & mj).bit_count(); ionly=mi.bit_count()-both; jonly=mj.bit_count()-both; outside=avail-(both+ionly+jonly)
    if ui<0 or uj<0: return -1,-999,(both,ionly,jonly,outside,0,0)
    max_inside=0; bestx=0
    for x in range(min(both,ui,uj)+1):
        val=x+min(ionly,ui-x)+min(jonly,uj-x)
        if val>max_inside: max_inside=val; bestx=x
    b=outside+max_inside
    return b,b,(both,ionly,jonly,outside,max_inside,bestx)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--frontier',type=Path,default=FRONT); ap.add_argument('--cover',type=Path,default=COVER); ap.add_argument('--take',type=int,default=64); ap.add_argument('--max-records',type=int,default=0); ap.add_argument('--out',type=Path,default=OUT)
    args=ap.parse_args(); t0=time.time(); rows=load_cover(args.cover,args.take); stats=Counter(); single_hist=Counter(); pair_hist=Counter(); examples=[]; row_hits=Counter(); pair_hits=Counter(); total=0
    with args.frontier.open() as f:
        for line in f:
            if args.max_records and total>=args.max_records: break
            rec=json.loads(line); total+=1; S=rec['force']; sset=set(S); need=rec['need']; avail=rec['avail']; next_min=rec['next_min']
            if avail<need:
                stats['cardinality_dead']+=1; continue
            stats['live']+=1
            future_mask=0
            for p in range(next_min,256): future_mask |= 1<<p
            # The rec avail already reflects cap<=5 saturation domain; we do not reconstruct it here.  For exactness,
            # use explicit future candidates if present; otherwise this script is intended for live-prefix files whose
            # available count was emitted after saturation but not candidate list.  Reconstructing requires analysis module.
            # Therefore this fast script supports only frontier records with future_points; if absent, fall back to the
            # precise but slower imported replayer.
            if 'future_points' in rec:
                future_mask=0
                for p in rec['future_points']: future_mask |= 1<<int(p)
            else:
                # Lazy import to reconstruct exactly.
                import importlib.util
                spec=importlib.util.spec_from_file_location('cmin', ROOT/'workspace/scripts/cover_conflict_minimize.py')
                m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
                if not hasattr(main,'repl'):
                    main.rows5=m.load_rows(m.ROWS5); main.cover_slow=m.load_rows(args.cover); main.repl=m.Replayer(main.rows5,main.cover_slow)
                excl=m.explicit_exclusions(rec); rep=main.repl.replay(S,excl)
                if rep['status']!='ok': stats['bad_replay_'+rep['status']]+=1; continue
                dom=rep['dom']; future_mask=0
                for k,w in enumerate(dom): future_mask |= int(w)<<(64*k)
                for p in range(1,next_min): future_mask &= ~(1<<p)
                avail=future_mask.bit_count(); need=19-len(sset)
            counts=[]; fmasks=[]; best_single=None
            for cap,mask,idx in rows:
                cnt=sum(1 for p in S if (mask>>p)&1); u=cap-cnt; fm=future_mask & mask; rin=fm.bit_count(); out=avail-rin; margin=u+out-need
                counts.append((u,cap,cnt,idx)); fmasks.append(fm)
                if best_single is None or margin<best_single[-1]: best_single=(idx,cap,cnt,u,rin,out,margin)
            sm=best_single[-1]; single_hist['neg' if sm<0 else str(min(sm,8))]+=1; sprune=sm<0; stats['single_prune']+=int(sprune)
            best_pair=None
            for a in range(len(rows)):
                ui,cap_i,cnt_i,idx_i=counts[a]
                for b in range(a+1,len(rows)):
                    uj,cap_j,cnt_j,idx_j=counts[b]
                    bound,_,parts=exact_pair_bound(avail,fmasks[a],fmasks[b],ui,uj)
                    margin=bound-need
                    if best_pair is None or margin<best_pair[13]:
                        both,ionly,jonly,outside,max_inside,bestx=parts
                        best_pair=(idx_i,idx_j,cap_i,cap_j,cnt_i,cnt_j,ui,uj,both,ionly,jonly,outside,bound,margin,max_inside,bestx)
            pm=best_pair[13]; pair_hist['neg' if pm<0 else str(min(pm,8))]+=1; pprune=pm<0
            stats['pair_prune']+=int(pprune); stats['pair_extra']+=int(pprune and not sprune)
            if pprune and not sprune:
                pair_hits[f'{best_pair[0]},{best_pair[1]}']+=1; row_hits[str(best_pair[0])]+=1; row_hits[str(best_pair[1])]+=1
                if len(examples)<50: examples.append({'idx':total-1,'force':S,'need':need,'avail':avail,'single_best':best_single,'pair_best':best_pair})
    out={'schema':'s0908_fast_pair_cover_stats_v1','frontier':str(args.frontier),'cover':str(args.cover),'cover_sha256':sha(args.cover),'take':args.take,'records_read':total,'stats':dict(stats),'single_margin_hist':dict(single_hist),'pair_margin_hist':dict(pair_hist),'pair_extra_examples_head':examples,'pair_hit_hist':dict(pair_hits),'row_hit_hist':dict(row_hits),'elapsed_sec':time.time()-t0,'note':'Exact reconstruction is used when frontier records omit future_points; this is slower but avoids treating numeric order as the whole domain.'}
    args.out.parent.mkdir(parents=True,exist_ok=True); args.out.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n'); print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__': main()
