#!/usr/bin/env python3
"""analysis seeded rank-one exchange search for rank 22.

A rank-22 decomposition is equivalent to a 22-dimensional space U containing
W=col(D) that is generated by rank-one 9x9 matrices.  This script constructs
U = W + span(13 rank-one seed columns), enumerates every rank-one matrix in U,
and tests whether those rank-one points span U.  Seeds are taken from the best
W-containing hyperplanes of known rank-23 spans and then perturbed by replacing
one seed with an arbitrary rank-one column.  This is a direct construction
search, not evidence against global existence when it fails.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import residual_repair_geometry as rg  # type: ignore
from rankone_lattice import (  # type: ignore
    echelon_add,
    echelon_reduce,
    independent_subset,
    rank_of_int_list,
    rank_ones_in_span,
    solve_and_verify,
)
from dependency_modW import functional_space, bitparity, make_Wcoord_basis, quotient_decomposition  # type: ignore

OUTDIR = Path('data/rankone_exchange')


def build_rank23_basis(terms):
    basis: Dict[int, Tuple[int,int]] = {}
    for i,(a,b,_c) in enumerate(terms):
        if not echelon_add(basis, rg.vec_mask9_to_outer81(a,b), 1<<i):
            raise RuntimeError('dependent rank23 source')
    return basis


def W_coords_in_basis(basis, W_cols):
    out=[]
    for w in W_cols:
        rem,tag=echelon_reduce(basis,w)
        if rem: raise RuntimeError('W not in source')
        out.append(tag)
    return out


def all_rankones_with_rank23_tags(basis):
    return rank_ones_in_span(basis)


def q_independent_seed(rankones, Wcoords, dim=13):
    Wb=make_Wcoord_basis(Wcoords)
    tags=[t for _a,_b,t in rankones]
    qtags,_wtags=quotient_decomposition(tags,Wb)
    items=[]
    for (a,b,t),q in zip(rankones,qtags):
        items.append((q,(a,b,t)))
    # prefer original source columns before extras for a stable seed, but still
    # choose only by quotient independence.
    items.sort(key=lambda it: ((it[1][2] & (it[1][2]-1)) != 0, it[1][2], it[1][0], it[1][1]))
    picked=[]; piv={}
    for q,payload in items:
        x=int(q)
        while x:
            p=x.bit_length()-1
            if p in piv: x ^= piv[p]
            else:
                piv[p]=x; picked.append(payload); break
        if len(picked)==dim: break
    if len(picked)!=dim:
        raise RuntimeError('could not pick q-independent seed')
    return picked


def build_U_basis(W_cols, seeds: Sequence[Tuple[int,int]]):
    basis: Dict[int, Tuple[int,int]]={}
    # tag W as coordinates 0..8 and seeds as 9..21
    for j,w in enumerate(W_cols):
        if not echelon_add(basis,int(w),1<<j):
            raise RuntimeError('dependent W')
    for i,(a,b) in enumerate(seeds):
        ok=echelon_add(basis,rg.vec_mask9_to_outer81(a,b),1<<(9+i))
        if not ok:
            return None
    if len(basis)!=9+len(seeds):
        return None
    return basis


def analyze_U(W_cols, seeds):
    basis=build_U_basis(W_cols,seeds)
    if basis is None:
        return {'valid_dim':False}
    S=rank_ones_in_span(basis)
    tags=[t for _a,_b,t in S]
    span_rank=rank_of_int_list(tags)
    Wb={}
    for j in range(9):
        echelon_add(Wb,1<<j,1<<j)
    qtags=[t>>9 for t in tags]  # only valid because W and seed tags are separated
    qrank=rank_of_int_list(qtags)
    out={'valid_dim':True,'rank_one_count':len(S),'rank_one_span_rank':span_rank,'q_rank':qrank,'W_from_relations_dim':span_rank-qrank}
    if span_rank>=22:
        picks=independent_subset([(t,(a,b)) for a,b,t in S],22)
        A=[a for a,_b in picks]; B=[b for _a,b in picks]
        vr=solve_and_verify(A,B)
        out['verify']=vr
    return out


def source_seed_records(name, terms, W_cols, max_hyperplanes=4):
    basis=build_rank23_basis(terms)
    Wcoords=W_coords_in_basis(basis,W_cols)
    S=all_rankones_with_rank23_tags(basis)
    phibasis=functional_space(Wcoords,len(terms))
    best=[]; best_rank=-1
    for phi in [x for x in range(1,1<<len(phibasis))]:
        f=0
        for i,b in enumerate(phibasis):
            if (phi>>i)&1: f ^= b
        kept=[ro for ro in S if not bitparity(f & ro[2])]
        r=rank_of_int_list([t for _a,_b,t in kept])
        if r>best_rank:
            best_rank=r; best=[(f,kept)]
        elif r==best_rank and len(best)<max_hyperplanes:
            best.append((f,kept))
    recs=[]
    for f,kept in best[:max_hyperplanes]:
        seed13=q_independent_seed(kept,Wcoords,13)
        recs.append({'source':name,'phi':int(f),'best_rank':int(best_rank),'kept_count':len(kept),'seed13_rank23_tags':[int(t) for _a,_b,t in seed13],'seed13_ab':[(int(a),int(b)) for a,b,_t in seed13]})
    return recs


def random_rankone(rng):
    return rng.randrange(1,512), rng.randrange(1,512)


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--sources',default='cn122_qmm,flip_rank23_text,pivot17_transformed_rank23')
    ap.add_argument('--trials-per-seed',type=int,default=1000)
    ap.add_argument('--seed',type=int,default=9031031)
    ap.add_argument('--outdir',type=Path,default=OUTDIR)
    args=ap.parse_args()
    args.outdir.mkdir(parents=True,exist_ok=True)
    rng=random.Random(args.seed)
    W_cols=rg.D_columns_as_ints()
    sources=rg.load_sources()
    seed_recs=[]
    for name in [x.strip() for x in args.sources.split(',') if x.strip()]:
        seed_recs.extend(source_seed_records(name,sources[name],W_cols))
    best={'rank_one_span_rank':-1,'rank_one_count':-1,'q_rank':-1,'W_from_relations_dim':-1}
    hist=Counter(); improvements=[]; witnesses=[]; tested=0; invalid=0
    t0=time.time()
    for si,rec in enumerate(seed_recs):
        base=[tuple(x) for x in rec['seed13_ab']]
        a0=analyze_U(W_cols,base)
        a0.update({'seed_index':si,'source':rec['source'],'phi':rec['phi'],'swap_pos':None,'trial':-1})
        hist[a0.get('rank_one_span_rank',-1)] += 1
        if a0.get('valid_dim') and (a0['rank_one_span_rank'],a0['rank_one_count'])>(best['rank_one_span_rank'],best['rank_one_count']):
            best={**a0,'seed_ab':base}
            improvements.append(best)
        if a0.get('verify',{}).get('status')=='VERIFIED': witnesses.append(a0['verify']); break
        for trial in range(args.trials_per_seed):
            pos=rng.randrange(13)
            new=list(base); new[pos]=random_rankone(rng)
            if new[pos] in base: continue
            tested+=1
            a=analyze_U(W_cols,new)
            if not a.get('valid_dim'):
                invalid+=1; continue
            a.update({'seed_index':si,'source':rec['source'],'phi':rec['phi'],'swap_pos':pos,'trial':trial})
            hist[a['rank_one_span_rank']] += 1
            key=(a['rank_one_span_rank'],a['W_from_relations_dim'],a['rank_one_count'],a['q_rank'])
            bkey=(best['rank_one_span_rank'],best.get('W_from_relations_dim',-1),best['rank_one_count'],best.get('q_rank',-1))
            if key>bkey:
                best={**a,'seed_ab':new}
                improvements.append(best)
                print('improve', {k:best[k] for k in ['rank_one_span_rank','rank_one_count','q_rank','W_from_relations_dim','source','seed_index','swap_pos','trial']}, flush=True)
            if a.get('verify',{}).get('status')=='VERIFIED':
                witnesses.append(a['verify']); break
        if witnesses: break
    out={'schema':'s0908_seeded_rankone_exchange_v1','meaning':'Seeded one-swap search in spaces U=W+span(13 rank-one columns). A VERIFIED witness is a rank-22 decomposition checked by Brent equations; failure is only search evidence.','parameters':vars(args),'seed_records':seed_recs,'tested_swaps':tested,'invalid_dimension_swaps':invalid,'span_rank_hist':{str(k):int(v) for k,v in sorted(hist.items())},'best':best,'improvements_tail':improvements[-20:],'witness_count':len(witnesses),'witnesses':witnesses,'elapsed_sec':time.time()-t0}
    op=args.outdir/'seeded_rankone_exchange.json'
    op.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    if witnesses:
        wp=args.outdir/'rank22_witness_from_exchange.json'; wp.write_text(json.dumps(witnesses[0],indent=2,sort_keys=True)+'\n')
    print(json.dumps({'status':'ok','out':str(op),'tested_swaps':tested,'invalid':invalid,'hist':out['span_rank_hist'],'best':{k:best.get(k) for k in ['rank_one_span_rank','rank_one_count','q_rank','W_from_relations_dim','source','seed_index','swap_pos','trial']},'witness_count':len(witnesses),'elapsed_sec':out['elapsed_sec']},indent=2,sort_keys=True))

if __name__=='__main__': main()
